import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

const HERO_SRC = "/hero-auth.webp";

export const heroSrc = HERO_SRC;

export const useAuthLayoutStyles = makeStyles({
  shell: {
    position: "relative",
    width: "100vw",
    height: "100vh",
    backgroundColor: tokens.colorBg0,
    color: tokens.colorText,
    overflowX: "hidden",
    overflowY: "hidden",
    fontFamily: tokens.fontBody,
  },
  hero: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center 35%",
    filter: "saturate(0.92) brightness(0.85)",
    transform: "scale(1.02)",
  },
  scrim: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    backgroundImage: `
      linear-gradient(180deg, rgba(5,7,6,0.55) 0%, rgba(5,7,6,0) 22%, rgba(5,7,6,0) 55%, rgba(5,7,6,0.7) 100%),
      linear-gradient(270deg, rgba(5,7,6,0.92) 0%, rgba(5,7,6,0.6) 30%, rgba(5,7,6,0.05) 65%, rgba(5,7,6,0) 100%)
    `,
  },
  grain: { opacity: 0.18 },
  brand: {
    position: "absolute",
    top: "28px",
    left: "32px",
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    zIndex: 3,
    pointerEvents: "none",
  },
  wordmark: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.32em",
    textTransform: "uppercase",
    color: tokens.colorTextDim,
  },
  panelWrap: {
    position: "relative",
    zIndex: 2,
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingTop: "32px",
    paddingRight: "8vw",
    paddingBottom: "32px",
    paddingLeft: "32px",
  },
  panel: {
    width: "100%",
    maxWidth: "420px",
    paddingTop: "40px",
    paddingRight: "36px",
    paddingBottom: "36px",
    paddingLeft: "36px",
    backgroundColor: "rgba(10, 13, 12, 0.62)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    borderRightColor: tokens.colorBorderSoft,
    borderBottomColor: tokens.colorBorderSoft,
    borderLeftColor: tokens.colorBorderSoft,
    borderRadius: tokens.radiusMd,
    backdropFilter: "blur(18px) saturate(1.2)",
    WebkitBackdropFilter: "blur(18px) saturate(1.2)",
    boxShadow: `0 30px 80px rgba(0,0,0,0.55), 0 0 0 1px rgba(255,255,255,0.02) inset, 0 0 60px ${tokens.colorGreenSoft}`,
  },
  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
    marginBottom: "10px",
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "44px",
    lineHeight: "0.98",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
    color: tokens.colorText,
    marginBottom: "10px",
  },
  subtitle: {
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    lineHeight: "1.5",
    color: tokens.colorTextDim,
    marginBottom: "28px",
  },
});
