import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useNotFoundStyles = makeStyles({
  shell: {
    height: "100%",
    position: "relative",
    overflowX: "hidden",
    overflowY: "hidden",
    backgroundColor: tokens.colorBg0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
  },
  grain: { opacity: 0.2 },
  glow: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    background: `radial-gradient(ellipse at center, ${tokens.colorGreenSoft} 0%, transparent 60%)`,
    pointerEvents: "none",
  },
  watermark: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: tokens.fontHead,
    fontSize: "32vw",
    color: tokens.colorText,
    opacity: 0.04,
    letterSpacing: "-0.04em",
    pointerEvents: "none",
    userSelect: "none",
  },
  content: {
    position: "relative",
    textAlign: "center",
    zIndex: 2,
    padding: "24px",
  },
  eyebrowGreen: { color: tokens.colorGreen },
  hero: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    color: tokens.colorText,
    letterSpacing: "-0.01em",
    marginTop: "12px",
    textTransform: "uppercase",
  },
  intro: {
    color: tokens.colorTextDim,
    maxWidth: "460px",
    marginTop: "8px",
    marginLeft: "auto",
    marginRight: "auto",
  },
  actionRow: {
    display: "flex",
    justifyContent: "center",
    columnGap: "12px",
    marginTop: "22px",
  },
  ghostBtn: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "18px",
    paddingRight: "18px",
    backgroundColor: "transparent",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    borderRadius: "2px",
    cursor: "pointer",
  },
  primaryLink: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "18px",
    paddingRight: "18px",
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    borderRadius: "2px",
    fontWeight: 700,
    textDecorationLine: "none",
  },
});
