import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useDevPanelStyles = makeStyles({
  root: {
    position: "fixed",
    right: "16px",
    bottom: "16px",
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    rowGap: "8px",
    fontFamily: tokens.fontMono,
  },
  toggle: {
    backgroundColor: tokens.colorSurface,
    color: tokens.colorGreen,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorGreen,
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    borderRadius: tokens.radiusFull,
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "12px",
    paddingRight: "12px",
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    cursor: "pointer",
    boxShadow: "0 8px 20px rgba(0, 0, 0, 0.45)",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreen,
      color: tokens.colorGreenInk,
    },
  },
  panel: {
    width: "280px",
    maxHeight: "65vh",
    backgroundColor: tokens.colorBg1,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    boxShadow: "0 16px 40px rgba(0, 0, 0, 0.55)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: tokens.colorSurface,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  headerTitle: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
    flexGrow: 1,
  },
  headerHint: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    color: tokens.colorTextFaint,
    letterSpacing: "0.06em",
  },
  closeBtn: {
    backgroundColor: "transparent",
    color: tokens.colorTextMuted,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: "4px",
    paddingRight: "4px",
    fontSize: "14px",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  list: {
    overflowY: "auto",
    paddingTop: "4px",
    paddingBottom: "4px",
  },
  group: {
    paddingTop: "8px",
    paddingBottom: "8px",
  },
  groupLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.22em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    paddingLeft: "14px",
    paddingRight: "14px",
    paddingBottom: "4px",
  },
  entry: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    width: "100%",
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "14px",
    paddingRight: "14px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    cursor: "pointer",
    textAlign: "left",
    textDecorationLine: "none",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreenSoft,
      color: tokens.colorGreen,
    },
  },
  entryActive: {
    color: tokens.colorGreen,
    backgroundColor: tokens.colorGreenSoft,
  },
  entryLabel: {
    flexGrow: 1,
  },
  entryPath: {
    fontSize: "9px",
    color: tokens.colorTextFaint,
    letterSpacing: "0.04em",
  },
});
