import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useHomePageStyles = makeStyles({
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflowX: "hidden",
    overflowY: "auto",
    backgroundColor: tokens.colorBg0,
    paddingLeft: "40px",
    paddingRight: "40px",
  },

  hero: {
    flexShrink: 0,
    height: "75vh",
    position: "relative",
    overflow: "hidden",
    borderRadius: "6px",
  },
  heroActive: {
    backgroundColor: tokens.colorBg0,
    borderRadius: 0,
    overflow: "visible",
  },
  heroPanelBg: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: tokens.colorBg0,
    backgroundImage: `radial-gradient(circle at 70% 35%, rgba(120, 200, 150, 0.07) 0%, transparent 55%), radial-gradient(circle, rgba(255,255,255,0.045) 1px, transparent 1px)`,
    backgroundSize: "100% 100%, 28px 28px",
    pointerEvents: "none",
    maskImage: "radial-gradient(ellipse 92% 88% at 50% 48%, #000 55%, transparent 100%)",
    WebkitMaskImage: "radial-gradient(ellipse 92% 88% at 50% 48%, #000 55%, transparent 100%)",
  },
  heroBody: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    paddingTop: `calc(${tokens.headerHeight} + 32px)`,
    paddingBottom: "20px",
    paddingLeft: "44px",
    paddingRight: "44px",
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    zIndex: 2,
  },
  greetingEyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
  },
  greeting: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.92",
    color: tokens.colorText,
    marginTop: "28px",
    letterSpacing: "-0.02em",
  },

  searchBar: {
    position: "absolute",
    top: `calc(${tokens.headerHeight} + 24px)`,
    right: "32px",
    zIndex: 3,
    width: "320px",
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    paddingRight: "12px",
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.42) 22%, rgba(20,28,24,0.42) 78%, rgba(20,28,24,0) 100%)",
    transitionProperty: "background-image",
    transitionDuration: tokens.transition,
  },
  searchBarFocused: {
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.7) 22%, rgba(20,28,24,0.7) 78%, rgba(20,28,24,0) 100%)",
  },
  searchIcon: {
    color: tokens.colorGreen,
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
  },
  searchInputWrap: {
    position: "relative",
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    height: "20px",
  },
  searchInput: {
    width: "100%",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    outlineStyle: "none",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.06em",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: "12px",
    "::placeholder": {
      color: tokens.colorTextMuted,
      letterSpacing: "0.14em",
      textTransform: "uppercase",
      fontSize: "10px",
    },
  },
  searchClear: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },

  noResults: {
    paddingTop: "40px",
    paddingBottom: "40px",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
    textAlign: "center",
  },
  searchResults: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
  },
  searchGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, 200px)",
    justifyContent: "start",
    columnGap: "16px",
    rowGap: "24px",
  },

  rowsScroll: {
    flexGrow: 1,
    marginTop: "-32vh",
    position: "relative",
    zIndex: 2,
    paddingTop: "20px",
    paddingBottom: "60px",
    display: "flex",
    flexDirection: "column",
    rowGap: "28px",
  },
  rowHeader: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorTextDim,
  },
});
