import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useHomePageStyles = makeStyles({
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflowX: "hidden",
    overflowY: "auto",
    backgroundColor: tokens.colorBg0,
    paddingLeft: "40px",
    paddingRight: "40px",
  },

  hero: {
    flexShrink: 0,
    height: "75vh",
    position: "relative",
    overflow: "hidden",
    borderRadius: "6px",
  },
  heroSlides: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflow: "hidden",
    zIndex: 0,
    // Elliptical alpha mask to blend edges instead of hard rectangle.
    maskImage:
      "radial-gradient(ellipse 95% 95% at 50% 50%, #000 55%, rgba(0,0,0,0.4) 80%, transparent 100%)",
    WebkitMaskImage:
      "radial-gradient(ellipse 95% 95% at 50% 50%, #000 55%, rgba(0,0,0,0.4) 80%, transparent 100%)",
  },
  heroImg: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "grayscale(1) brightness(0.55)",
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: "0.9s",
    transitionTimingFunction: "ease",
    animationName: {
      "0%": { transform: "scale(1.06) translate(-0.8%, -0.6%)" },
      "100%": { transform: "scale(1.06) translate(0.8%, 0.6%)" },
    },
    animationDuration: "20s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
    animationDirection: "alternate",
  },
  heroImgActive: {
    opacity: 1,
  },
  heroImgFading: {
    opacity: 0,
  },
  heroEdgeFade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    zIndex: 1,
    backgroundImage: `linear-gradient(to bottom, rgba(5,7,6,0.55) 0%, transparent 28%, transparent 62%, rgba(5,7,6,0.78) 100%), linear-gradient(to right, transparent 0%, transparent 80%, rgba(5,7,6,0.55) 100%)`,
  },
  heroBottomFade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    zIndex: 1,
    backgroundImage: `linear-gradient(180deg, transparent 50%, rgba(5,7,6,0.8) 88%, ${tokens.colorBg0} 100%), linear-gradient(90deg, ${tokens.colorBg0} 0%, rgba(5,7,6,0.85) 22%, transparent 55%)`,
  },
  slideDots: {
    display: "flex",
    columnGap: "8px",
  },
  slideDot: {
    height: "3px",
    borderRadius: "2px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    cursor: "pointer",
    transitionProperty: "width, background-color",
    transitionDuration: tokens.transitionSlow,
  },
  slideDotActive: {
    width: "26px",
    backgroundColor: tokens.colorTextFaint,
    position: "relative",
    overflow: "hidden",
  },
  slideDotFill: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: tokens.colorGreen,
    transformOrigin: "left center",
    animationName: {
      "0%": { transform: "scaleX(0)" },
      "100%": { transform: "scaleX(1)" },
    },
    animationDuration: "7s",
    animationTimingFunction: "linear",
    animationFillMode: "forwards",
  },
  slideDotInactive: {
    width: "8px",
    backgroundColor: tokens.colorTextFaint,
  },
  heroActive: {
    backgroundColor: tokens.colorBg0,
    borderRadius: 0,
    overflow: "visible",
    // Idle mode pins the hero at 75vh so the rotating poster fills it.
    // In search/filter mode there's no poster, just the panel + a
    // gradient-noise backdrop — let the hero collapse to the panel's
    // natural height so the action buttons sit close to the rows
    // header rather than floating at 75vh.
    height: "auto",
  },
  heroPanelBg: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: tokens.colorBg0,
    backgroundImage: `radial-gradient(circle at 70% 35%, rgba(120, 200, 150, 0.07) 0%, transparent 55%), radial-gradient(circle, rgba(255,255,255,0.045) 1px, transparent 1px)`,
    backgroundSize: "100% 100%, 28px 28px",
    pointerEvents: "none",
    maskImage: "radial-gradient(ellipse 92% 88% at 50% 48%, #000 55%, transparent 100%)",
    WebkitMaskImage: "radial-gradient(ellipse 92% 88% at 50% 48%, #000 55%, transparent 100%)",
  },
  heroBody: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    paddingTop: `calc(${tokens.headerHeight} + 32px)`,
    paddingBottom: "20px",
    paddingLeft: "44px",
    paddingRight: "44px",
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    zIndex: 2,
  },
  // In search/filter mode, pull heroBody into normal flow; position: relative preserves z-index.
  heroBodyFlow: {
    position: "relative",
    top: "auto",
    right: "auto",
    bottom: "auto",
    left: "auto",
  },
  greetingEyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
  },
  greeting: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.92",
    color: tokens.colorText,
    marginTop: "28px",
    letterSpacing: "-0.02em",
  },

  searchBar: {
    position: "absolute",
    top: `calc(${tokens.headerHeight} + 24px)`,
    right: "32px",
    zIndex: 3,
    width: "320px",
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    paddingRight: "12px",
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.42) 22%, rgba(20,28,24,0.42) 78%, rgba(20,28,24,0) 100%)",
    transitionProperty: "background-image",
    transitionDuration: tokens.transition,
  },
  searchBarFocused: {
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.7) 22%, rgba(20,28,24,0.7) 78%, rgba(20,28,24,0) 100%)",
  },
  searchIcon: {
    color: tokens.colorGreen,
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
  },
  searchInputWrap: {
    position: "relative",
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    height: "20px",
  },
  searchMirror: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: "translateY(-50%)",
    visibility: "hidden",
    pointerEvents: "none",
    whiteSpace: "pre",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.06em",
  },
  searchCaret: {
    position: "absolute",
    top: "50%",
    width: "7px",
    height: "14px",
    marginTop: "-7px",
    backgroundColor: tokens.colorGreen,
    borderTopLeftRadius: "1px",
    borderTopRightRadius: "1px",
    borderBottomLeftRadius: "1px",
    borderBottomRightRadius: "1px",
    pointerEvents: "none",
    boxShadow: `0 0 6px ${tokens.colorGreen}, 0 0 14px ${tokens.colorGreenGlow}`,
    animationName: {
      "0%, 100%": { opacity: "1", transform: "scaleY(1)" },
      "50%": { opacity: "0.25", transform: "scaleY(0.86)" },
    },
    animationDuration: "1.05s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  searchInput: {
    width: "100%",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    outlineStyle: "none",
    caretColor: "transparent",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.06em",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: "12px",
    "::placeholder": {
      color: tokens.colorTextMuted,
      letterSpacing: "0.14em",
      textTransform: "uppercase",
      fontSize: "10px",
    },
  },
  searchClear: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },

  noResults: {
    paddingTop: "40px",
    paddingBottom: "40px",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
    textAlign: "center",
  },
  searchResults: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
  },
  searchGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, 200px)",
    justifyContent: "start",
    columnGap: "16px",
    rowGap: "24px",
  },

  rowsScroll: {
    flexGrow: 1,
    marginTop: "-32vh",
    position: "relative",
    zIndex: 2,
    paddingTop: "20px",
    paddingBottom: "60px",
    display: "flex",
    flexDirection: "column",
    rowGap: "28px",
  },
  // In search/filter mode, reset negative marginTop to avoid covering SearchSlide action buttons.
  rowsScrollFlat: {
    marginTop: 0,
    zIndex: "auto",
  },
  rowHeader: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorTextDim,
  },
});
