import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useDesignSystemStyles = makeStyles({
  shell: {
    height: "100%",
    overflowY: "auto",
    paddingTop: `calc(${tokens.headerHeight} + 32px)`,
    paddingBottom: "80px",
    paddingLeft: "40px",
    paddingRight: "40px",
    boxSizing: "border-box",
  },
  eyebrow: { color: tokens.colorGreen },
  hero: {
    fontFamily: tokens.fontHead,
    fontSize: "56px",
    lineHeight: "0.92",
    letterSpacing: "-0.01em",
    color: tokens.colorText,
    marginTop: "12px",
    marginBottom: "8px",
  },
  intro: {
    color: tokens.colorTextDim,
    maxWidth: "720px",
    lineHeight: "1.6",
  },

  // Section
  section: { marginTop: "56px" },
  sectionHead: {
    display: "flex",
    alignItems: "baseline",
    columnGap: "16px",
    marginBottom: "18px",
  },
  sectionLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
  },
  sectionTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "24px",
    letterSpacing: "-0.01em",
    color: tokens.colorText,
  },

  // Color tokens grid
  tokenGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: "12px",
  },
  tokenCard: {
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    padding: "10px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    borderRightColor: tokens.colorBorderSoft,
    borderBottomColor: tokens.colorBorderSoft,
    borderLeftColor: tokens.colorBorderSoft,
    backgroundColor: tokens.colorSurface,
  },
  swatch: {
    width: "36px",
    height: "36px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
  },
  tokenInfo: { minWidth: 0 },
  tokenName: { fontSize: "11px", color: tokens.colorText },
  tokenCode: {
    fontSize: "9px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tokenUsage: {
    fontSize: "10px",
    color: tokens.colorTextFaint,
    marginTop: "2px",
  },

  // Type scale
  typeStack: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
  },
  typeHint: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.12em",
    marginTop: "4px",
  },

  // Spacing scale
  spacingStack: {
    display: "flex",
    flexDirection: "column",
    rowGap: "12px",
  },
  spacingRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "14px",
  },
  spacingBar: {
    height: "18px",
    backgroundColor: tokens.colorGreen,
    flexShrink: 0,
  },
  spacingLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextDim,
  },

  // Logo grid
  logoIntro: {
    color: tokens.colorTextMuted,
    marginBottom: "16px",
    fontSize: "13px",
  },
  logoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(380px, 1fr))",
    gap: "18px",
  },

  // Context frames
  contextFrame: {
    backgroundColor: tokens.colorSurface,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "4px",
  },
  iconRow: {
    padding: "28px",
    display: "flex",
    columnGap: "24px",
    alignItems: "center",
    justifyContent: "center",
  },
  iconTile: {
    background: `linear-gradient(160deg, ${tokens.colorSurface}, ${tokens.colorBg0})`,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: `0 14px 30px -16px ${tokens.colorGreenGlow}`,
  },

  // Header lockup
  headerLockup: {
    paddingTop: "28px",
    paddingBottom: "28px",
    paddingLeft: "32px",
    paddingRight: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brand: {
    fontFamily: tokens.fontHead,
    fontSize: "38px",
    letterSpacing: "-0.03em",
    display: "flex",
    alignItems: "baseline",
  },
  brandX: { color: tokens.colorGreen },
  brandWord: { color: tokens.colorText },
  navList: {
    display: "flex",
    columnGap: "22px",
    fontSize: "12px",
    fontFamily: tokens.fontMono,
    color: tokens.colorTextDim,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },

  // Brand swatches
  swatchPanel: {
    padding: "24px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: "14px",
  },
  swatchTile: {
    width: "100%",
    aspectRatio: "1.4/1",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    marginBottom: "8px",
  },
  swatchName: { fontSize: "11px", color: tokens.colorText, fontWeight: 600 },
  swatchCode: {
    fontSize: "9px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
  },
});
