import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useSettingsStyles = makeStyles({
  shell: {
    height: "100%",
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
    overflowX: "hidden",
    overflowY: "hidden",
  },
  nav: {
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: tokens.colorBorder,
    backgroundColor: tokens.colorBg1,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
  },
  navHeading: { marginBottom: "14px" },
  navItem: {
    paddingTop: "9px",
    paddingBottom: "9px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    fontSize: "12px",
    textAlign: "left",
    borderRadius: "2px",
    cursor: "pointer",
  },
  navItemActive: {
    backgroundColor: tokens.colorGreenSoft,
    color: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
  },
  body: {
    overflowY: "auto",
    paddingTop: "32px",
    paddingBottom: "32px",
    paddingLeft: "40px",
    paddingRight: "40px",
  },
  sectionEyebrow: { color: tokens.colorGreen },
  sectionTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "40px",
    color: tokens.colorText,
    marginTop: "12px",
    marginBottom: "24px",
    textTransform: "uppercase",
    letterSpacing: "-0.01em",
  },
  sectionWrap: { maxWidth: "640px" },

  row: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    columnGap: "16px",
    paddingTop: "14px",
    paddingBottom: "14px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  rowLabel: { fontSize: "13px", color: tokens.colorText },
  rowHint: { fontSize: "11px", color: tokens.colorTextMuted, marginTop: "4px" },

  toggle: {
    width: "38px",
    height: "20px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "999px",
    position: "relative",
    cursor: "pointer",
    backgroundColor: tokens.colorSurface2,
  },
  toggleOn: { backgroundColor: tokens.colorGreen },
  toggleKnob: {
    position: "absolute",
    top: "2px",
    left: "2px",
    width: "14px",
    height: "14px",
    borderRadius: "999px",
    backgroundColor: tokens.colorTextDim,
    transitionProperty: "left",
    transitionDuration: tokens.transition,
  },
  toggleKnobOn: {
    left: "20px",
    backgroundColor: tokens.colorGreenInk,
  },

  selector: {
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "12px",
    paddingRight: "12px",
    backgroundColor: tokens.colorSurface2,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "2px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorText,
    letterSpacing: "0.08em",
  },

  dangerOutlineBtn: {
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: "transparent",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorRed,
    borderRightColor: tokens.colorRed,
    borderBottomColor: tokens.colorRed,
    borderLeftColor: tokens.colorRed,
    color: tokens.colorRed,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    borderRadius: "2px",
    cursor: "pointer",
  },
  dangerSolidBtn: {
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: tokens.colorRed,
    color: "#fff",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    borderRadius: "2px",
    cursor: "pointer",
    fontWeight: 700,
  },
});
