import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useDirectoryBrowserStyles = makeStyles({
  panel: {
    width: "100%",
    minWidth: "320px",
    backgroundColor: tokens.colorBg1,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    boxShadow: "0 16px 40px rgba(0, 0, 0, 0.45)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  breadcrumb: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.06em",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    backgroundColor: tokens.colorSurface,
    display: "flex",
    alignItems: "center",
    columnGap: "4px",
    overflowX: "auto",
    whiteSpace: "nowrap",
  },
  crumbBtn: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    color: tokens.colorTextDim,
    fontFamily: "inherit",
    fontSize: "inherit",
    letterSpacing: "inherit",
    cursor: "pointer",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorGreen },
  },
  crumbCurrent: {
    color: tokens.colorText,
  },
  crumbSep: {
    color: tokens.colorTextFaint,
  },
  list: {
    maxHeight: "260px",
    overflowY: "auto",
    paddingTop: "4px",
    paddingBottom: "4px",
  },
  entry: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    width: "100%",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "14px",
    paddingRight: "14px",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    cursor: "pointer",
    textAlign: "left",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreenSoft,
      color: tokens.colorGreen,
    },
  },
  entryUp: {
    color: tokens.colorTextMuted,
    fontStyle: "italic",
  },
  entryIcon: {
    color: tokens.colorTextDim,
    flexShrink: 0,
  },
  empty: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextFaint,
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "14px",
    paddingRight: "14px",
    textAlign: "center",
    fontStyle: "italic",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    backgroundColor: tokens.colorSurface,
  },
  actionsHint: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextFaint,
    letterSpacing: "0.06em",
    flexGrow: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cancelBtn: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  selectBtn: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "4px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
});
