import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useWatchlistStyles = makeStyles({
  page: {
    height: "100%",
    overflowX: "hidden",
    overflowY: "auto",
    backgroundColor: tokens.colorBg0,
    paddingTop: `calc(${tokens.headerHeight} + 60px)`,
    paddingBottom: "80px",
    paddingLeft: "60px",
    paddingRight: "60px",
    boxSizing: "border-box",
  },

  header: {
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    marginBottom: "44px",
  },
  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.95",
    color: tokens.colorText,
    letterSpacing: "-0.02em",
  },
  subtitle: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.06em",
    color: tokens.colorTextMuted,
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "24px",
  },

  tile: {
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    backgroundColor: "transparent",
    color: "inherit",
    textDecorationLine: "none",
    transitionProperty: "transform",
    transitionDuration: tokens.transition,
    ":hover": {
      transform: "translateY(-3px)",
    },
  },
  tileFrame: {
    position: "relative",
    aspectRatio: "2/3",
    overflowX: "hidden",
    overflowY: "hidden",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    backgroundColor: tokens.colorSurface,
    transitionProperty: "border-color, box-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
      boxShadow: `0 8px 24px ${tokens.colorGreenSoft}`,
    },
  },
  tileImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  progressTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "3px",
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  progressFill: {
    height: "100%",
    backgroundColor: tokens.colorGreen,
  },
  ratingBadge: {
    position: "absolute",
    top: "8px",
    right: "8px",
    backgroundColor: "rgba(0,0,0,0.7)",
    color: tokens.colorYellow,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    paddingTop: "3px",
    paddingBottom: "3px",
    paddingLeft: "6px",
    paddingRight: "6px",
    borderRadius: "2px",
    display: "flex",
    alignItems: "center",
    columnGap: "4px",
  },
  tileMeta: {
    display: "flex",
    flexDirection: "column",
    rowGap: "3px",
  },
  tileTitle: {
    fontSize: "13px",
    color: tokens.colorText,
  },
  tileSubtitle: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.06em",
  },
  tileAdded: {
    fontSize: "10px",
    color: tokens.colorTextFaint,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.04em",
  },
});
