import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useFilmDetailsOverlayStyles = makeStyles({
  overlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflowX: "hidden",
    overflowY: "auto",
    backgroundColor: tokens.colorBg0,
  },
  hero: {
    position: "relative",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
  },
  poster: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    viewTransitionName: "film-backdrop",
    // Slow, subtle breathing — gentle scale pulse from 1.02 → 1.05 → 1.02
    // with a barely perceptible pan riding along the same cycle. ~14s per
    // breath keeps it well under the conscious-noticing threshold; the
    // ease-in-out shape mimics chest-rise / chest-fall.
    animationName: {
      "0%": { transform: "scale(1.02) translate(-0.2%, -0.15%)" },
      "50%": { transform: "scale(1.05) translate(0.2%, 0.15%)" },
      "100%": { transform: "scale(1.02) translate(-0.2%, -0.15%)" },
    },
    animationDuration: "14s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
  gradient: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    backgroundImage: `linear-gradient(180deg, rgba(5,7,6,0.45) 0%, transparent 25%, transparent 38%, rgba(5,7,6,0.85) 72%, ${tokens.colorBg0} 100%), linear-gradient(90deg, rgba(5,7,6,0.5) 0%, transparent 35%)`,
  },
  // (`back` button removed — the AppHeader's home logo already provides
  // the back-to-home affordance. Only the X close remains, shifted below
  // the header so it doesn't sit underneath the chrome.)
  close: {
    position: "absolute",
    // 52px header + 12px breathing room. Shared `tokens.headerHeight`
    // would inline as the wrong CSS shape here; the literal value keeps
    // the absolute positioning explicit.
    top: "64px",
    right: "28px",
    width: "40px",
    height: "40px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.45)",
    color: tokens.colorText,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "50%",
    cursor: "pointer",
    zIndex: 4,
    transitionProperty: "background-color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(0,0,0,0.7)",
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
    },
  },
  content: {
    position: "absolute",
    left: "60px",
    right: "60px",
    bottom: "72px",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    rowGap: "14px",
    maxWidth: "720px",
  },
  chips: {
    display: "flex",
    columnGap: "8px",
    alignItems: "center",
  },
  rating: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "5px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorYellow,
    paddingLeft: "4px",
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "72px",
    lineHeight: "0.95",
    color: tokens.colorText,
    letterSpacing: "-0.02em",
  },
  metaRow: {
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    letterSpacing: "0.08em",
    color: tokens.colorTextDim,
    textTransform: "uppercase",
  },
  director: {
    fontSize: "13px",
    color: tokens.colorTextMuted,
  },
  directorName: {
    color: tokens.colorText,
  },
  plot: {
    fontSize: "15px",
    lineHeight: "1.55",
    color: tokens.colorTextDim,
    maxWidth: "640px",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
    marginTop: "8px",
  },
  playCta: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "10px",
    backgroundColor: "rgba(255,255,255,0.12)",
    color: "#fff",
    paddingTop: "14px",
    paddingBottom: "14px",
    paddingLeft: "26px",
    paddingRight: "30px",
    borderRadius: "999px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "rgba(255,255,255,0.30)",
    borderRightColor: "rgba(255,255,255,0.18)",
    borderBottomColor: "rgba(255,255,255,0.10)",
    borderLeftColor: "rgba(255,255,255,0.18)",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    fontWeight: 600,
    textDecorationLine: "none",
    cursor: "pointer",
    backdropFilter: "blur(20px) saturate(180%)",
    WebkitBackdropFilter: "blur(20px) saturate(180%)",
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.35), inset 0 -1px 0 rgba(0,0,0,0.20), 0 10px 32px rgba(0,0,0,0.45)",
    transitionProperty:
      "transform, box-shadow, background-color, color, border-color, text-shadow",
    transitionDuration: "0.18s",
    transitionTimingFunction: "ease-out",
    "& svg": {
      display: "block",
      color: "rgba(255,255,255,0.55)",
      filter:
        "drop-shadow(0 1px 0.5px rgba(255,255,255,0.45)) drop-shadow(0 -1px 0.5px rgba(0,0,0,0.55))",
      transitionProperty: "color, filter",
      transitionDuration: "0.18s",
    },
    // Hover tints the glass with the green accent — restrained, no
    // halo. The earlier neon-sign treatment proved too bright; we keep
    // a faint inner-edge highlight + a subtle outer drop, no large
    // ambient bloom.
    ":hover": {
      transform: "translateY(-1px)",
      backgroundColor: "oklch(0.78 0.20 150 / 0.14)",
      borderTopColor: "oklch(0.78 0.20 150 / 0.40)",
      borderRightColor: "oklch(0.78 0.20 150 / 0.28)",
      borderBottomColor: "oklch(0.78 0.20 150 / 0.18)",
      borderLeftColor: "oklch(0.78 0.20 150 / 0.28)",
      color: tokens.colorGreen,
      textShadow: `0 0 4px oklch(0.78 0.20 150 / 0.35)`,
      boxShadow: `inset 0 1px 0 oklch(0.78 0.20 150 / 0.40), inset 0 -1px 0 rgba(0,0,0,0.20), 0 8px 22px rgba(0,0,0,0.45), 0 0 14px oklch(0.78 0.20 150 / 0.18)`,
    },
    ":hover svg": {
      color: tokens.colorGreen,
      filter: `drop-shadow(0 0 3px oklch(0.78 0.20 150 / 0.45))`,
    },
    ":active": {
      transform: "translateY(0) scale(0.98)",
    },
  },
  secondaryCta: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    backgroundColor: "transparent",
    color: "rgba(255,255,255,0.75)",
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    "& svg": {
      width: "12px",
      height: "12px",
      display: "block",
      color: "rgba(255,255,255,0.55)",
      transitionProperty: "color",
      transitionDuration: tokens.transition,
    },
    "& span": {
      textDecorationLine: "underline",
      textDecorationColor: "rgba(255,255,255,0.25)",
      textDecorationThickness: "1px",
      textUnderlineOffset: "4px",
      transitionProperty: "text-decoration-color",
      transitionDuration: tokens.transition,
    },
    ":hover": {
      color: "#fff",
    },
    ":hover svg": {
      color: tokens.colorGreen,
    },
    ":hover span": {
      textDecorationColor: tokens.colorGreen,
    },
  },
  filename: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.06em",
    color: tokens.colorTextFaint,
  },
  scrollHint: {
    position: "absolute",
    right: 0,
    bottom: "-44px",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    animationName: {
      "0%, 100%": { opacity: 0.4, transform: "translateY(0)" },
      "50%": { opacity: 0.85, transform: "translateY(3px)" },
    },
    animationDuration: "1.8s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  suggestions: {
    paddingTop: "40px",
    paddingBottom: "60px",
    paddingLeft: "60px",
    paddingRight: "60px",
    backgroundColor: tokens.colorBg0,
  },

  seasonsRail: {
    position: "absolute",
    top: "84px",
    right: "60px",
    bottom: "72px",
    width: "380px",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "rgba(5, 7, 6, 0.72)",
    backdropFilter: "blur(14px) saturate(160%)",
    WebkitBackdropFilter: "blur(14px) saturate(160%)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    boxShadow: "0 16px 40px rgba(0,0,0,0.45)",
    overflow: "hidden",
  },
  seasonsRailHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "14px",
    paddingBottom: "14px",
    paddingLeft: "16px",
    paddingRight: "16px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    backgroundColor: "rgba(20, 24, 26, 0.5)",
  },
  seasonsRailLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.22em",
    color: tokens.colorText,
    textTransform: "uppercase",
  },
  seasonsRailStat: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.16em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
  },
  seasonsRailScroll: {
    flexGrow: 1,
    overflowY: "auto",
    overflowX: "hidden",
  },
  contentWithRail: {
    maxWidth: "560px",
  },
});
