import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useFilmDetailsOverlayStyles = makeStyles({
  overlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflowX: "hidden",
    overflowY: "auto",
    backgroundColor: tokens.colorBg0,
  },
  hero: {
    position: "relative",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
  },
  poster: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    viewTransitionName: "film-backdrop",
    animationName: {
      "0%": { transform: "scale(1.04) translate(-0.4%, -0.3%)" },
      "100%": { transform: "scale(1.04) translate(0.4%, 0.3%)" },
    },
    animationDuration: "26s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
    animationDirection: "alternate",
  },
  gradient: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    backgroundImage: `linear-gradient(180deg, rgba(5,7,6,0.45) 0%, transparent 25%, transparent 38%, rgba(5,7,6,0.85) 72%, ${tokens.colorBg0} 100%), linear-gradient(90deg, rgba(5,7,6,0.5) 0%, transparent 35%)`,
  },
  back: {
    position: "absolute",
    top: "24px",
    left: "28px",
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "12px",
    paddingRight: "16px",
    backgroundColor: "rgba(0,0,0,0.45)",
    color: tokens.colorText,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "999px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    cursor: "pointer",
    zIndex: 4,
    transitionProperty: "background-color, border-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(0,0,0,0.7)",
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
      color: tokens.colorGreen,
    },
  },
  close: {
    position: "absolute",
    top: "24px",
    right: "28px",
    width: "40px",
    height: "40px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.45)",
    color: tokens.colorText,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "50%",
    cursor: "pointer",
    zIndex: 4,
    transitionProperty: "background-color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(0,0,0,0.7)",
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
    },
  },
  content: {
    position: "absolute",
    left: "60px",
    right: "60px",
    bottom: "72px",
    zIndex: 3,
    display: "flex",
    flexDirection: "column",
    rowGap: "14px",
    maxWidth: "720px",
  },
  chips: {
    display: "flex",
    columnGap: "8px",
    alignItems: "center",
  },
  rating: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "5px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorYellow,
    paddingLeft: "4px",
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "72px",
    lineHeight: "0.95",
    color: tokens.colorText,
    letterSpacing: "-0.02em",
  },
  metaRow: {
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    letterSpacing: "0.08em",
    color: tokens.colorTextDim,
    textTransform: "uppercase",
  },
  director: {
    fontSize: "13px",
    color: tokens.colorTextMuted,
  },
  directorName: {
    color: tokens.colorText,
  },
  plot: {
    fontSize: "15px",
    lineHeight: "1.55",
    color: tokens.colorTextDim,
    maxWidth: "640px",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
    marginTop: "8px",
  },
  playCta: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "10px",
    backgroundColor: "rgba(255,255,255,0.12)",
    color: "#fff",
    paddingTop: "14px",
    paddingBottom: "14px",
    paddingLeft: "26px",
    paddingRight: "30px",
    borderRadius: "999px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "rgba(255,255,255,0.30)",
    borderRightColor: "rgba(255,255,255,0.18)",
    borderBottomColor: "rgba(255,255,255,0.10)",
    borderLeftColor: "rgba(255,255,255,0.18)",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    fontWeight: 600,
    textDecorationLine: "none",
    cursor: "pointer",
    backdropFilter: "blur(20px) saturate(180%)",
    WebkitBackdropFilter: "blur(20px) saturate(180%)",
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.35), inset 0 -1px 0 rgba(0,0,0,0.20), 0 10px 32px rgba(0,0,0,0.45)",
    transitionProperty:
      "transform, box-shadow, background-color, color, border-color, text-shadow",
    transitionDuration: "0.18s",
    transitionTimingFunction: "ease-out",
    "& svg": {
      display: "block",
      color: "rgba(255,255,255,0.55)",
      filter:
        "drop-shadow(0 1px 0.5px rgba(255,255,255,0.45)) drop-shadow(0 -1px 0.5px rgba(0,0,0,0.55))",
      transitionProperty: "color, filter",
      transitionDuration: "0.18s",
    },
    // Hover lights up the glass with the green accent — reads like a
    // neon sign coming on. The glow + saturated inner shadows + green
    // text-shadow give the lit-from-within feel.
    ":hover": {
      transform: "translateY(-1px)",
      backgroundColor: "oklch(0.78 0.20 150 / 0.18)",
      borderTopColor: "oklch(0.78 0.20 150 / 0.55)",
      borderRightColor: "oklch(0.78 0.20 150 / 0.4)",
      borderBottomColor: "oklch(0.78 0.20 150 / 0.25)",
      borderLeftColor: "oklch(0.78 0.20 150 / 0.4)",
      color: tokens.colorGreen,
      textShadow: `0 0 6px ${tokens.colorGreenGlow}, 0 0 18px ${tokens.colorGreen}`,
      boxShadow: `inset 0 1px 0 oklch(0.78 0.20 150 / 0.55), inset 0 -1px 0 rgba(0,0,0,0.20), 0 14px 40px rgba(0,0,0,0.55), 0 0 32px ${tokens.colorGreenGlow}, 0 0 80px oklch(0.78 0.20 150 / 0.30)`,
    },
    ":hover svg": {
      color: tokens.colorGreen,
      filter: `drop-shadow(0 0 4px ${tokens.colorGreen}) drop-shadow(0 0 12px ${tokens.colorGreenGlow})`,
    },
    ":active": {
      transform: "translateY(0) scale(0.98)",
    },
  },
  filename: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.06em",
    color: tokens.colorTextFaint,
  },
  scrollHint: {
    position: "absolute",
    right: 0,
    bottom: "-44px",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    animationName: {
      "0%, 100%": { opacity: 0.4, transform: "translateY(0)" },
      "50%": { opacity: 0.85, transform: "translateY(3px)" },
    },
    animationDuration: "1.8s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  suggestions: {
    paddingTop: "40px",
    paddingBottom: "60px",
    paddingLeft: "60px",
    paddingRight: "60px",
    backgroundColor: tokens.colorBg0,
  },
});
