import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useFilmVariantsStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    rowGap: "8px",
    marginTop: "12px",
  },
  heading: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.55)",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
  },
  row: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "10px",
    paddingRight: "12px",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "rgba(255,255,255,0.06)",
    borderRightColor: "rgba(255,255,255,0.06)",
    borderBottomColor: "rgba(255,255,255,0.06)",
    borderLeftColor: "rgba(255,255,255,0.06)",
    borderRadius: tokens.radiusSm,
    color: tokens.colorText,
    cursor: "pointer",
    textAlign: "left",
    transitionProperty: "background-color, border-color, transform",
    transitionDuration: "0.15s",
    ":hover": {
      backgroundColor: "rgba(255,255,255,0.06)",
      borderTopColor: "rgba(255,255,255,0.12)",
      borderRightColor: "rgba(255,255,255,0.12)",
      borderBottomColor: "rgba(255,255,255,0.12)",
      borderLeftColor: "rgba(255,255,255,0.12)",
    },
  },
  rowSelected: {
    backgroundColor: "rgba(120, 200, 140, 0.10)",
    borderTopColor: tokens.colorGreen,
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
  },
  dot: {
    flex: "0 0 auto",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "rgba(255,255,255,0.18)",
    transitionProperty: "background-color, box-shadow",
    transitionDuration: "0.15s",
  },
  tokens: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: "10px",
    rowGap: "2px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.06em",
    color: "rgba(255,255,255,0.75)",
  },
  token: {
    "::after": {
      content: '"·"',
      marginLeft: "10px",
      color: "rgba(255,255,255,0.25)",
    },
    ":last-child::after": {
      content: '""',
    },
  },
});
