import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

const GRAIN_URL =
  "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E\")";

export const useVideoAreaStyles = makeStyles({
  root: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflowX: "hidden",
    overflowY: "hidden",
    backgroundColor: "#000",
  },

  backdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "brightness(0.85) contrast(1.05)",
    viewTransitionName: "film-backdrop",
    zIndex: 0,
  },

  grain: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: "none",
    backgroundImage: GRAIN_URL,
    opacity: 0.18,
    mixBlendMode: "overlay",
    zIndex: 2,
  },

  videoWrapper: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },

  letterTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "80px",
    background: "linear-gradient(180deg, rgba(0,0,0,0.85), transparent)",
    pointerEvents: "none",
    zIndex: 3,
  },
  letterBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "220px",
    background: "linear-gradient(0deg, rgba(0,0,0,0.92), transparent)",
    pointerEvents: "none",
    zIndex: 3,
  },

  fade: {
    opacity: 1,
    transitionProperty: "opacity",
    transitionDuration: "0.3s",
  },
  fadeHidden: {
    opacity: 0,
    pointerEvents: "none",
  },

  topbar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "26px",
    paddingRight: "26px",
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    zIndex: 10,
    color: "#fff",
  },
  topbarBtn: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    color: "rgba(255,255,255,0.85)",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "8px",
    paddingRight: "8px",
    borderRadius: "999px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    filter: "drop-shadow(0 2px 6px rgba(0,0,0,0.6))",
    transitionProperty: "color, filter, transform",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    ":hover": {
      color: "#fff",
      filter: "drop-shadow(0 0 12px rgba(255,255,255,0.65)) drop-shadow(0 2px 6px rgba(0,0,0,0.6))",
    },
    ":active": {
      transform: "scale(0.94)",
    },
  },
  titleOverlay: {
    position: "absolute",
    bottom: "130px",
    left: "26px",
    right: "26px",
    zIndex: 9,
    pointerEvents: "none",
    color: "#fff",
  },

  filmMetaSpacer: {
    marginBottom: "18px",
  },

  episodeBadge: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "10px",
    marginBottom: "10px",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
    textShadow: "0 2px 8px rgba(0,0,0,0.6)",
  },
  episodeBadgeCode: {
    paddingTop: "3px",
    paddingBottom: "3px",
    paddingLeft: "8px",
    paddingRight: "8px",
    backgroundColor: "rgba(5, 7, 6, 0.55)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorGreen,
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    borderRadius: tokens.radiusSm,
    color: tokens.colorGreen,
    fontWeight: 600,
  },
  episodeBadgeTitle: {
    color: "rgba(255,255,255,0.85)",
  },

  filmTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.92",
    color: "#fff",
    letterSpacing: "-0.01em",
    marginBottom: "6px",
    textShadow: "0 4px 24px rgba(0,0,0,0.6)",
    textTransform: "uppercase",
  },
  filmMeta: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: "rgba(255,255,255,0.7)",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
});
