import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useDetailPaneStyles = makeStyles({
  pane: {
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.colorBorder,
    display: "flex",
    flexDirection: "column",
    backgroundColor: tokens.colorBg1,
    overflowX: "hidden",
    overflowY: "hidden",
    height: "100%",
  },
  posterFrame: {
    height: "220px",
    position: "relative",
    flexShrink: 0,
  },
  posterImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  posterFade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    background: `linear-gradient(180deg, transparent 50%, ${tokens.colorBg1})`,
  },
  closeBtn: {
    position: "absolute",
    top: "12px",
    right: "12px",
    width: "26px",
    height: "26px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    backgroundColor: "rgba(0,0,0,0.6)",
    color: tokens.colorTextDim,
    borderRadius: "3px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  body: {
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "22px",
    paddingRight: "22px",
    flexGrow: 1,
    overflowY: "auto",
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "18px",
    marginBottom: "16px",
  },
  playAction: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "4px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color, opacity",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  editAction: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: "rgba(232, 238, 232, 0.35)",
    textDecorationThickness: "1px",
    textUnderlineOffset: "4px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color, opacity",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorGreen,
      textDecorationColor: tokens.colorGreen,
    },
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "32px",
    lineHeight: "1",
    color: tokens.colorText,
    letterSpacing: "-0.01em",
    marginBottom: "4px",
    textTransform: "uppercase",
  },
  subhead: {
    fontSize: "11px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.1em",
    marginBottom: "14px",
    textTransform: "uppercase",
  },
  techChips: {
    display: "flex",
    columnGap: "6px",
    rowGap: "6px",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  ratingRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    marginBottom: "14px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextDim,
  },
  ratingValue: { color: tokens.colorYellow },
  divider: { color: tokens.colorTextFaint },
  status: { color: tokens.colorGreen },
  plot: {
    fontSize: "12px",
    color: tokens.colorTextDim,
    lineHeight: "1.55",
    marginBottom: "14px",
  },
  sectionLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.22em",
    color: tokens.colorTextFaint,
    marginBottom: "8px",
    textTransform: "uppercase",
  },
  castChips: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: "6px",
    rowGap: "6px",
    marginBottom: "14px",
  },
  fileBlock: {
    backgroundColor: tokens.colorSurface,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    borderRightColor: tokens.colorBorderSoft,
    borderBottomColor: tokens.colorBorderSoft,
    borderLeftColor: tokens.colorBorderSoft,
    padding: "12px",
    fontSize: "10px",
    fontFamily: tokens.fontMono,
    color: tokens.colorTextDim,
    lineHeight: "1.7",
  },
  fileMeta: {
    display: "flex",
    columnGap: "12px",
    rowGap: "4px",
    marginTop: "6px",
    color: tokens.colorTextMuted,
    flexWrap: "wrap",
  },
});
