import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useToastStyles = makeStyles({
  // Fixed bottom-right stack, above all page content but click-through
  // except on the toasts themselves.
  viewport: {
    position: "fixed",
    right: "24px",
    bottom: "24px",
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    pointerEvents: "none",
    maxWidth: "380px",
  },
  toast: {
    pointerEvents: "auto",
    display: "flex",
    alignItems: "flex-start",
    columnGap: "10px",
    paddingTop: "11px",
    paddingBottom: "11px",
    paddingLeft: "14px",
    paddingRight: "12px",
    backgroundColor: tokens.colorSurface,
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderRadius: tokens.radiusMd,
    boxShadow: "0 8px 28px rgba(0, 0, 0, 0.45)",
    animationName: {
      from: { opacity: 0, transform: "translateY(8px)" },
      to: { opacity: 1, transform: "translateY(0)" },
    },
    animationDuration: tokens.transitionSlow,
    animationTimingFunction: "ease-out",
  },
  toastSuccess: { borderLeftColor: tokens.colorGreen },
  toastError: { borderLeftColor: tokens.colorRed },
  toastInfo: { borderLeftColor: tokens.colorTextMuted },
  glyph: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    lineHeight: "18px",
    flexShrink: 0,
  },
  glyphSuccess: { color: tokens.colorGreen },
  glyphError: { color: tokens.colorRed },
  glyphInfo: { color: tokens.colorTextDim },
  message: {
    flexGrow: 1,
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    lineHeight: "18px",
    color: tokens.colorText,
  },
  dismiss: {
    flexShrink: 0,
    backgroundColor: "transparent",
    borderTopStyle: "none",
    borderRightStyle: "none",
    borderBottomStyle: "none",
    borderLeftStyle: "none",
    cursor: "pointer",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    lineHeight: "18px",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: "4px",
    paddingRight: "4px",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
});
