import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const usePlayerStyles = makeStyles({
  // Top-level player container — chrome shown vs hidden
  shell: {
    width: "100vw",
    height: "100vh",
    backgroundColor: "#000",
    position: "relative",
    overflowX: "hidden",
    overflowY: "hidden",
    display: "grid",
    gridTemplateColumns: "1fr 290px",
    transitionProperty: "grid-template-columns",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease",
    cursor: "default",
  },
  shellChromeHidden: {
    gridTemplateColumns: "1fr 0px",
    cursor: "none",
  },

  unknownFilmBox: { padding: "32px" },

  // Video area
  videoArea: {
    position: "relative",
    overflowX: "hidden",
    overflowY: "hidden",
  },
  backdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "brightness(0.85) contrast(1.05)",
    viewTransitionName: "film-backdrop",
  },
  grain: {
    opacity: 0.18,
    mixBlendMode: "overlay",
  },

  // Letterbox / chrome fade
  letterTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "80px",
    background: "linear-gradient(180deg, rgba(0,0,0,0.85), transparent)",
  },
  letterBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "220px",
    background: "linear-gradient(0deg, rgba(0,0,0,0.92), transparent)",
  },
  fade: {
    opacity: 1,
    transitionProperty: "opacity",
    transitionDuration: "0.3s",
  },
  fadeHidden: {
    opacity: 0,
    pointerEvents: "none",
  },

  // Idle / loading overlay
  idleOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 8,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    color: tokens.colorText,
    cursor: "pointer",
  },
  spinner: {
    width: "56px",
    height: "56px",
    borderRadius: "999px",
    borderTopWidth: "3px",
    borderRightWidth: "3px",
    borderBottomWidth: "3px",
    borderLeftWidth: "3px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderRightColor: "rgba(255,255,255,0.3)",
    borderBottomColor: "rgba(255,255,255,0.3)",
    borderLeftColor: "rgba(255,255,255,0.3)",
    borderTopColor: tokens.colorGreen,
    animationName: { to: { transform: "rotate(360deg)" } },
    animationDuration: "0.9s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  bigPlay: {
    width: "80px",
    height: "80px",
    borderRadius: "999px",
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: `0 0 60px ${tokens.colorGreenGlow}`,
  },
  bigPlayIcon: { transform: "scale(2)" },

  // Topbar
  topbar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "26px",
    paddingRight: "26px",
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    zIndex: 10,
    color: "#fff",
  },
  flexFill: { flexGrow: 1 },
  topbarBtn: {
    backgroundColor: "rgba(0,0,0,0.45)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "rgba(255,255,255,0.18)",
    borderRightColor: "rgba(255,255,255,0.18)",
    borderBottomColor: "rgba(255,255,255,0.18)",
    borderLeftColor: "rgba(255,255,255,0.18)",
    color: "#fff",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderRadius: "2px",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    cursor: "pointer",
  },
  topbarStatus: { color: "rgba(255,255,255,0.6)" },

  // Bottom controls
  bottomControls: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: "20px",
    paddingBottom: "24px",
    paddingLeft: "26px",
    paddingRight: "26px",
    zIndex: 10,
  },
  filmTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.92",
    color: "#fff",
    letterSpacing: "-0.01em",
    marginBottom: "6px",
    textShadow: "0 4px 24px rgba(0,0,0,0.6)",
    textTransform: "uppercase",
  },
  filmMeta: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: "rgba(255,255,255,0.7)",
    letterSpacing: "0.18em",
    marginBottom: "18px",
    textTransform: "uppercase",
  },
  progressRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "14px",
    marginBottom: "14px",
  },
  timeLabel: {
    color: "#fff",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
  },
  timeLabelDim: {
    color: "rgba(255,255,255,0.6)",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
  },
  progressTrack: {
    flexGrow: 1,
    height: "3px",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: "2px",
    position: "relative",
  },
  progressBuffered: {
    width: "62%",
    height: "100%",
    backgroundColor: "rgba(255,255,255,0.4)",
  },
  progressPlayed: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "53%",
    height: "100%",
    backgroundColor: tokens.colorGreen,
    boxShadow: `0 0 8px ${tokens.colorGreenGlow}`,
  },
  progressKnob: {
    position: "absolute",
    left: "53%",
    top: "50%",
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: tokens.colorGreen,
    transform: "translate(-50%, -50%)",
    boxShadow: `0 0 12px ${tokens.colorGreenGlow}`,
  },
  controlsRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    color: "#fff",
  },
  ctrlBtn: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    color: "#fff",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "12px",
    paddingRight: "12px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.12em",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    borderRadius: "2px",
  },
  ctrlBtnPlay: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
  },
  volumeBar: {
    width: "80px",
    height: "3px",
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  volumeFill: {
    width: "70%",
    height: "100%",
    backgroundColor: "#fff",
  },
  chipSmall: { fontSize: "9px" },

  // Side panel
  sidePanel: {
    backgroundColor: tokens.colorBg1,
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.colorBorder,
    display: "flex",
    flexDirection: "column",
    overflowX: "hidden",
    overflowY: "hidden",
    opacity: 1,
    transitionProperty: "opacity",
    transitionDuration: "0.3s",
  },
  sidePanelHidden: {
    opacity: 0,
    pointerEvents: "none",
  },
  sidePanelHeader: {
    paddingTop: "20px",
    paddingBottom: "14px",
    paddingLeft: "18px",
    paddingRight: "18px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  nowPlayingEyebrow: { color: tokens.colorGreen },
  sideTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "26px",
    color: tokens.colorText,
    marginTop: "8px",
    letterSpacing: "-0.01em",
    lineHeight: "1",
    textTransform: "uppercase",
  },
  sideMeta: {
    fontSize: "11px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.08em",
    marginTop: "6px",
    textTransform: "uppercase",
  },
  sidePlot: {
    fontSize: "11px",
    color: tokens.colorTextDim,
    marginTop: "10px",
    lineHeight: "1.5",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflowY: "hidden",
  },
  sideBody: {
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "18px",
    paddingRight: "18px",
    flexGrow: 1,
    overflowY: "auto",
  },
  eyebrowSpace: { marginBottom: "10px" },
  eyebrowSpaceTop: { marginTop: "18px", marginBottom: "10px" },
  upNextEmpty: {
    fontSize: "11px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
  },
  upNextRow: {
    display: "grid",
    gridTemplateColumns: "44px 1fr 22px",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    alignItems: "center",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  upNextPoster: {
    width: "44px",
    height: "62px",
    objectFit: "cover",
  },
  upNextTitle: { fontSize: "12px", color: tokens.colorText },
  upNextSub: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    marginTop: "2px",
  },
  upNextPlay: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    backgroundColor: tokens.colorGreenSoft,
    color: tokens.colorGreen,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorGreenDeep,
    borderRightColor: tokens.colorGreenDeep,
    borderBottomColor: tokens.colorGreenDeep,
    borderLeftColor: tokens.colorGreenDeep,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textDecorationLine: "none",
  },
  watchlistRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    columnGap: "10px",
    paddingTop: "6px",
    paddingBottom: "6px",
    alignItems: "center",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  watchlistTitle: { fontSize: "12px", color: tokens.colorText },
  watchlistStatus: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    marginTop: "2px",
    letterSpacing: "0.08em",
  },
  watchlistStatusOnDisk: {
    color: tokens.colorGreen,
  },
  watchlistPlay: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.18em",
    color: tokens.colorGreen,
    textDecorationLine: "none",
  },

  footerRow: {
    paddingTop: "12px",
    paddingBottom: "12px",
    paddingLeft: "18px",
    paddingRight: "18px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    display: "flex",
    columnGap: "8px",
  },
  vlcBtn: {
    flexGrow: 1,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "10px",
    paddingRight: "10px",
    backgroundColor: "transparent",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    borderRadius: "2px",
    cursor: "pointer",
  },
  backBtn: {
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: tokens.colorSurface2,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    borderRadius: "2px",
    textTransform: "uppercase",
    cursor: "pointer",
  },
});
