import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useProfilesPageStyles = makeStyles({
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
  },
  splitBody: {
    display: "grid",
    gridTemplateColumns: "1fr 0px 0px",
    flexGrow: 1,
    minHeight: 0,
    transitionProperty: "grid-template-columns",
    transitionDuration: tokens.transitionSlow,
    transitionTimingFunction: "ease",
  },
  splitBodyOpen: {},
  resizeHandle: {
    backgroundColor: tokens.colorBorder,
    cursor: "col-resize",
    transitionProperty: "background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreen,
    },
  },
  breadcrumb: {
    height: "38px",
    paddingLeft: "24px",
    paddingRight: "24px",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
    flexShrink: 0,
  },
  breadcrumbScanning: {
    marginLeft: "auto",
    color: tokens.colorGreen,
  },
  crumbDim: { color: tokens.colorTextDim },
  crumbBright: { color: tokens.colorText },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
    flexShrink: 0,
  },
  footerCta: {
    color: tokens.colorGreen,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
});
