import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useControlBarStyles = makeStyles({
  // Transparent: VideoArea provides the letterbox-bottom darkening gradient.
  root: {
    position: "absolute",
    bottom: "0",
    left: "0",
    right: "0",
    paddingTop: "20px",
    paddingBottom: "24px",
    paddingLeft: "26px",
    paddingRight: "26px",
    transitionProperty: "opacity",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease",
    zIndex: 10,
  },
  rootHidden: {
    opacity: "0",
    pointerEvents: "none",
  },

  progressRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "14px",
    marginBottom: "14px",
  },
  timeLabel: {
    color: "#fff",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.02em",
  },
  timeLabelDim: {
    color: "rgba(255,255,255,0.6)",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.02em",
  },
  track: {
    flexGrow: 1,
    position: "relative",
    height: "3px",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: "2px",
    cursor: "pointer",
    transitionProperty: "height",
    transitionDuration: tokens.transition,
    ":hover": {
      height: "5px",
    },
  },
  trackFill: {
    position: "absolute",
    left: "0",
    top: "0",
    height: "100%",
    backgroundColor: tokens.colorGreen,
    boxShadow: `0 0 8px ${tokens.colorGreenGlow}`,
    borderRadius: "2px",
    pointerEvents: "none",
  },
  trackKnob: {
    position: "absolute",
    top: "50%",
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: tokens.colorGreen,
    boxShadow: `0 0 12px ${tokens.colorGreenGlow}`,
    transform: "translate(-50%, -50%)",
    pointerEvents: "none",
  },
  trackTooltip: {
    position: "absolute",
    bottom: "calc(100% + 10px)",
    transform: "translateX(-50%)",
    backgroundColor: tokens.colorSurface2,
    color: "#fff",
    fontSize: "11px",
    fontFamily: tokens.fontMono,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.02em",
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: "8px",
    paddingRight: "8px",
    borderRadius: tokens.radiusSm,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    pointerEvents: "none",
    whiteSpace: "nowrap",
    zIndex: 10,
  },

  controlsRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    color: "#fff",
  },
  flexFill: {
    flexGrow: 1,
  },

  ctrlBtn: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    color: "#fff",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "12px",
    paddingRight: "12px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.12em",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    borderRadius: "2px",
    transitionProperty: "color, background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(255,255,255,0.08)",
    },
  },
  ctrlBtnPlay: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    transitionProperty: "transform, box-shadow, background-color",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
    boxShadow: `0 4px 14px ${tokens.colorGreenSoft}`,
    ":hover": {
      backgroundColor: tokens.colorGreen,
      transform: "scale(1.06)",
      boxShadow: `0 6px 20px ${tokens.colorGreenGlow}, 0 0 28px ${tokens.colorGreenSoft}`,
    },
    ":active": {
      transform: "scale(0.96)",
    },
  },
  ctrlBtnPlayIdle: {
    animationName: {
      "0%, 100%": {
        boxShadow: `0 4px 14px ${tokens.colorGreenSoft}`,
        transform: "scale(1)",
      },
      "50%": {
        boxShadow: `0 6px 22px ${tokens.colorGreenGlow}, 0 0 32px ${tokens.colorGreenSoft}`,
        transform: "scale(1.04)",
      },
    },
    animationDuration: "2.4s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },

  volumeGroup: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },
  volumeSlider: {
    cursor: "pointer",
    height: "3px",
    transitionProperty: "width, opacity",
    transitionDuration: "0.2s",
    accentColor: tokens.colorGreen,
  },

  resWrapper: {
    position: "relative",
  },
  resChip: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
    backgroundColor: tokens.colorGreenSoft,
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: "8px",
    paddingRight: "8px",
    borderRadius: tokens.radiusSm,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorGreenDeep,
    borderRightColor: tokens.colorGreenDeep,
    borderBottomColor: tokens.colorGreenDeep,
    borderLeftColor: tokens.colorGreenDeep,
    cursor: "pointer",
  },
  resMenu: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    right: "0",
    backgroundColor: tokens.colorSurface2,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusMd,
    overflow: "hidden",
    minWidth: "100px",
    zIndex: 100,
  },
  resItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    color: "rgba(255,255,255,0.7)",
    fontSize: "12px",
    cursor: "pointer",
    textAlign: "left",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(255,255,255,0.05)",
      color: "#fff",
    },
  },
  resItemActive: {
    color: tokens.colorGreen,
    backgroundColor: tokens.colorGreenSoft,
  },

  loadingSpinner: {
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    borderTopWidth: "2px",
    borderRightWidth: "2px",
    borderBottomWidth: "2px",
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorGreenInk,
    borderRightColor: "rgba(5, 7, 6, 0.3)",
    borderBottomColor: "rgba(5, 7, 6, 0.3)",
    borderLeftColor: "rgba(5, 7, 6, 0.3)",
    animationName: { to: { transform: "rotate(360deg)" } },
    animationDuration: "0.75s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
  },
});
