import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useFeedbackDialogStyles = makeStyles({
  overlay: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: tokens.space5,
  },
  panel: {
    width: "100%",
    maxWidth: "420px",
    backgroundColor: tokens.colorBg1,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusMd,
    boxShadow: "0 16px 40px rgba(0, 0, 0, 0.45)",
    display: "flex",
    flexDirection: "column",
    rowGap: tokens.space3,
    paddingTop: tokens.space5,
    paddingBottom: tokens.space5,
    paddingLeft: tokens.space5,
    paddingRight: tokens.space5,
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "20px",
    letterSpacing: "0.02em",
    color: tokens.colorText,
    margin: 0,
  },
  subtitle: {
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    color: tokens.colorTextDim,
    margin: 0,
  },
  stars: {
    display: "flex",
    columnGap: "4px",
  },
  star: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    fontSize: "26px",
    lineHeight: 1,
    color: tokens.colorTextFaint,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: "2px",
    paddingRight: "2px",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
  },
  starFilled: {
    color: tokens.colorYellow,
  },
  message: {
    width: "100%",
    minHeight: "84px",
    resize: "vertical",
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    paddingTop: tokens.space2,
    paddingBottom: tokens.space2,
    paddingLeft: tokens.space2,
    paddingRight: tokens.space2,
    boxSizing: "border-box",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    columnGap: tokens.space2,
  },
  cancelBtn: {
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.08em",
    paddingTop: tokens.space2,
    paddingBottom: tokens.space2,
    paddingLeft: tokens.space3,
    paddingRight: tokens.space3,
  },
  submitBtn: {
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    paddingTop: tokens.space2,
    paddingBottom: tokens.space2,
    paddingLeft: tokens.space5,
    paddingRight: tokens.space5,
    ":disabled": {
      opacity: 0.4,
      cursor: "not-allowed",
    },
  },
  thanks: {
    fontFamily: tokens.fontBody,
    fontSize: "14px",
    color: tokens.colorGreen,
    textAlign: "center",
    paddingTop: tokens.space2,
    paddingBottom: tokens.space2,
  },
});
