import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useAccountMenuStyles = makeStyles({
  menu: {
    position: "absolute",
    top: "calc(100% + 10px)",
    right: 0,
    width: "240px",
    backgroundColor: tokens.colorBg1,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    boxShadow: "0 16px 40px rgba(0, 0, 0, 0.55)",
    zIndex: 20,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  identity: {
    paddingTop: "12px",
    paddingBottom: "12px",
    paddingLeft: "14px",
    paddingRight: "14px",
    display: "flex",
    alignItems: "center",
    columnGap: "12px",
    backgroundColor: tokens.colorSurface,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  initials: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundImage: `linear-gradient(140deg, ${tokens.colorGreenDeep}, ${tokens.colorGreen})`,
    color: tokens.colorGreenInk,
    fontFamily: tokens.fontMono,
    fontWeight: 700,
    fontSize: "13px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  identityText: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  name: {
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    color: tokens.colorText,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  email: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.06em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  list: {
    paddingTop: "4px",
    paddingBottom: "4px",
  },
  item: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    width: "100%",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    paddingRight: "14px",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    textDecorationLine: "none",
    cursor: "pointer",
    textAlign: "left",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreenSoft,
      color: tokens.colorGreen,
    },
  },
  itemDanger: {
    color: tokens.colorTextDim,
    ":hover": {
      backgroundColor: "rgba(255, 93, 108, 0.1)",
      color: tokens.colorRed,
    },
  },
  itemArrow: {
    marginLeft: "auto",
    color: tokens.colorTextFaint,
    fontFamily: tokens.fontMono,
  },
});
