import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";
import { PROFILE_GRID_COLUMNS } from "../../pages/Profiles/grid.js";

export const useProfileRowStyles = makeStyles({
  block: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  header: {
    display: "grid",
    gridTemplateColumns: PROFILE_GRID_COLUMNS,
    paddingTop: "11px",
    paddingBottom: "11px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    alignItems: "center",
    cursor: "pointer",
    backgroundColor: "transparent",
    transitionProperty: "background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(232, 238, 232, 0.04)",
    },
  },
  headerExpanded: {
    backgroundColor: tokens.colorSurface,
    ":hover": {
      backgroundColor: tokens.colorSurface,
    },
  },
  chevron: {
    color: tokens.colorTextMuted,
    transform: "rotate(0)",
    transitionProperty: "transform",
    transitionDuration: tokens.transition,
    display: "inline-flex",
  },
  chevronOpen: { transform: "rotate(90deg)" },
  name: { fontSize: "13px", color: tokens.colorText },
  path: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    marginTop: "2px",
    letterSpacing: "0.04em",
  },
  scanRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorGreen,
  },
  scanSpinner: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    borderTopWidth: "1.5px",
    borderRightWidth: "1.5px",
    borderBottomWidth: "1.5px",
    borderLeftWidth: "1.5px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "transparent",
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    animationName: { to: { transform: "rotate(360deg)" } },
    animationDuration: "0.9s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  matchRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },
  matchTrack: {
    flexGrow: 1,
    height: "3px",
    backgroundColor: tokens.colorSurface2,
    borderRadius: "2px",
    overflowX: "hidden",
    overflowY: "hidden",
  },
  matchFill: {
    height: "100%",
    backgroundColor: tokens.colorGreen,
  },
  matchFillWarn: { backgroundColor: tokens.colorYellow },
  matchPct: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    minWidth: "38px",
    textAlign: "right",
  },
  matchPctWarn: { color: tokens.colorYellow },
  size: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextDim,
  },
  rowEnd: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    color: tokens.colorTextMuted,
    textAlign: "right",
    letterSpacing: "0.12em",
  },
  editLink: {
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "3px",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  filmsList: {
    paddingLeft: "30px",
    backgroundColor: tokens.colorBg1,
  },
});
