import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useErrorPageStyles = makeStyles({
  shell: {
    minHeight: "100vh",
    width: "100%",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: tokens.colorBg1,
    color: tokens.colorText,
    paddingTop: tokens.headerHeight,
    paddingLeft: "24px",
    paddingRight: "24px",
    paddingBottom: "40px",
  },
  panel: {
    width: "100%",
    maxWidth: "560px",
    borderLeftWidth: "4px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.colorRed,
    paddingLeft: "28px",
  },
  eyebrow: { color: tokens.colorRed },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.95",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
    color: tokens.colorText,
    marginTop: "12px",
    marginBottom: "16px",
  },
  body: {
    fontFamily: tokens.fontBody,
    fontSize: "14px",
    lineHeight: "1.6",
    color: tokens.colorTextDim,
    marginBottom: "20px",
    margin: 0,
  },
  detailsToggle: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "6px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "0",
    paddingRight: "0",
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    cursor: "pointer",
    marginTop: "12px",
    ":hover": { color: tokens.colorText },
  },
  stack: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    lineHeight: "1.8",
    color: tokens.colorTextDim,
    backgroundColor: tokens.colorSurface,
    paddingTop: "12px",
    paddingBottom: "12px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    marginTop: "12px",
    marginBottom: "0",
    overflowX: "auto",
    whiteSpace: "pre",
  },
  actions: {
    display: "flex",
    columnGap: "16px",
    marginTop: "28px",
  },
  ctaSecondary: {
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorText,
    textUnderlineOffset: "5px",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorTextDim },
  },
  ctaPrimary: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "0",
    paddingRight: "0",
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
});
