import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useProfilesStyles = makeStyles({
  splitBody: {
    display: "grid",
    gridTemplateColumns: "1fr 0px 0px",
    height: "100%",
    transitionProperty: "grid-template-columns",
    transitionDuration: tokens.transitionSlow,
    transitionTimingFunction: "ease",
  },
  splitBodyOpen: {},
  isResizing: {
    transitionProperty: "none",
  },
  leftCol: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
  },
  resizeHandle: {
    backgroundColor: tokens.colorBorder,
    cursor: "col-resize",
    transitionProperty: "background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreen,
    },
  },
  hero: {
    height: "220px",
    position: "relative",
    overflow: "hidden",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  heroSlides: {
    position: "absolute",
    inset: "0",
  },
  heroImg: {
    position: "absolute",
    inset: "0",
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "brightness(0.55)",
    opacity: "0",
    transitionProperty: "opacity",
    transitionDuration: "0.8s",
    transitionTimingFunction: "ease",
    animationName: {
      "0%": { transform: "scale(1.06) translate(-0.8%, -0.6%)" },
      "100%": { transform: "scale(1.06) translate(0.8%, 0.6%)" },
    },
    animationDuration: "16s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
    animationDirection: "alternate",
  },
  heroImgActive: {
    opacity: "1",
  },
  heroImgFading: {
    opacity: "0",
  },
  heroEdgeFade: {
    position: "absolute",
    inset: "0",
    pointerEvents: "none",
    backgroundImage:
      "linear-gradient(to bottom, rgba(5,7,6,0.55) 0%, transparent 28%, transparent 62%, rgba(5,7,6,0.78) 100%), linear-gradient(to right, transparent 0%, transparent 80%, rgba(5,7,6,0.55) 100%)",
    backgroundSize: "100% 115%, 115% 100%",
    backgroundPosition: "0% 0%, 0% 0%",
    backgroundRepeat: "no-repeat, no-repeat",
    animationName: {
      "0%": { backgroundPosition: "0% 0%, 0% 0%" },
      "50%": { backgroundPosition: "0% 100%, 100% 0%" },
      "100%": { backgroundPosition: "0% 0%, 0% 0%" },
    },
    animationDuration: "18s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
  heroGradient: {
    position: "absolute",
    inset: "0",
    background: `linear-gradient(90deg, ${tokens.colorBg0} 0%, rgba(5,7,6,0.85) 30%, transparent 65%)`,
  },
  heroBody: {
    position: "absolute",
    inset: "0",
    paddingTop: "30px",
    paddingBottom: "30px",
    paddingLeft: "36px",
    paddingRight: "36px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    zIndex: 2,
  },
  greetingEyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
  },
  greeting: {
    fontFamily: tokens.fontHead,
    fontSize: "56px",
    lineHeight: "0.92",
    color: tokens.colorText,
    marginTop: "12px",
    letterSpacing: "-0.01em",
  },
  slideDots: {
    display: "flex",
    columnGap: "8px",
  },
  slideDot: {
    height: "3px",
    borderRadius: "2px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    cursor: "pointer",
    transitionProperty: "width, background-color",
    transitionDuration: tokens.transitionSlow,
  },
  slideDotActive: {
    width: "22px",
    backgroundColor: tokens.colorGreen,
  },
  slideDotInactive: {
    width: "6px",
    backgroundColor: tokens.colorTextFaint,
  },
  breadcrumb: {
    height: "38px",
    paddingLeft: "24px",
    paddingRight: "24px",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  breadcrumbScanning: {
    marginLeft: "auto",
    color: tokens.colorGreen,
  },
  colHeader: {
    display: "grid",
    gridTemplateColumns: "30px 1.3fr 0.7fr 0.6fr 80px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.18em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  rowsScroll: {
    flex: 1,
    overflowY: "auto",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  footerCta: {
    color: tokens.colorGreen,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },

  // Breadcrumb spans (a couple of color overrides)
  crumbDim: { color: tokens.colorTextDim },
  crumbBright: { color: tokens.colorText },

  // Profile expand row
  profileBlock: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  profileHeader: {
    display: "grid",
    gridTemplateColumns: "30px 1.3fr 0.7fr 0.6fr 80px",
    paddingTop: "11px",
    paddingBottom: "11px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    alignItems: "center",
    cursor: "pointer",
    backgroundColor: "transparent",
  },
  profileHeaderExpanded: {
    backgroundColor: tokens.colorSurface,
  },
  chevron: {
    color: tokens.colorTextMuted,
    transform: "rotate(0)",
    transitionProperty: "transform",
    transitionDuration: tokens.transition,
    display: "inline-flex",
  },
  chevronOpen: { transform: "rotate(90deg)" },
  profileName: { fontSize: "13px", color: tokens.colorText },
  profilePath: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    marginTop: "2px",
    letterSpacing: "0.04em",
  },
  scanRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorGreen,
  },
  scanSpinner: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    borderTopWidth: "1.5px",
    borderRightWidth: "1.5px",
    borderBottomWidth: "1.5px",
    borderLeftWidth: "1.5px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "transparent",
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    animationName: { to: { transform: "rotate(360deg)" } },
    animationDuration: "0.9s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  matchRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },
  matchTrack: {
    flexGrow: 1,
    height: "3px",
    backgroundColor: tokens.colorSurface2,
    borderRadius: "2px",
    overflowX: "hidden",
    overflowY: "hidden",
  },
  matchFill: {
    height: "100%",
    backgroundColor: tokens.colorGreen,
  },
  matchFillWarn: { backgroundColor: tokens.colorYellow },
  matchPct: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    minWidth: "38px",
    textAlign: "right",
  },
  matchPctWarn: { color: tokens.colorYellow },
  size: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextDim,
  },
  rowEnd: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    color: tokens.colorTextMuted,
    textAlign: "right",
    letterSpacing: "0.12em",
  },

  // Films within an expanded profile
  filmsList: {
    paddingLeft: "30px",
    backgroundColor: tokens.colorBg1,
  },
  filmRow: {
    display: "grid",
    gridTemplateColumns: "30px 1.3fr 0.7fr 0.6fr 80px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    alignItems: "center",
    backgroundColor: "transparent",
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: "transparent",
    cursor: "pointer",
  },
  filmRowSelected: {
    backgroundColor: tokens.colorGreenSoft,
    borderLeftColor: tokens.colorGreen,
  },
  filmThumb: {
    width: "26px",
    height: "38px",
    objectFit: "cover",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
  },
  filmTitle: { fontSize: "12px", color: tokens.colorText },
  filmYear: { color: tokens.colorTextMuted },
  filmMeta: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    marginTop: "2px",
  },
  chipRow: { display: "flex", columnGap: "4px" },
  chipSmall: {
    fontSize: "9px",
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: "5px",
    paddingRight: "5px",
  },
  ratingCell: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextDim,
    display: "flex",
    alignItems: "center",
    columnGap: "4px",
  },
  ratingValue: { color: tokens.colorYellow },
  playCell: { textAlign: "right" },
  playLink: {
    display: "inline-block",
    backgroundColor: "transparent",
    color: tokens.colorTextMuted,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: "10px",
    paddingRight: "10px",
    borderRadius: "2px",
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    textDecorationLine: "none",
  },
  playLinkActive: {
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },
});
