import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";
import { PROFILE_GRID_COLUMNS } from "./grid.js";

export const useProfilesStyles = makeStyles({
  splitBody: {
    display: "grid",
    gridTemplateColumns: "1fr 0px 0px",
    height: "100%",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
    transitionProperty: "grid-template-columns",
    transitionDuration: tokens.transitionSlow,
    transitionTimingFunction: "ease",
  },
  splitBodyOpen: {},
  isResizing: {
    transitionProperty: "none",
  },
  leftCol: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
  },
  resizeHandle: {
    backgroundColor: tokens.colorBorder,
    cursor: "col-resize",
    transitionProperty: "background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreen,
    },
  },
  breadcrumb: {
    height: "38px",
    paddingLeft: "24px",
    paddingRight: "24px",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  breadcrumbScanning: {
    marginLeft: "auto",
    color: tokens.colorGreen,
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "24px",
    paddingRight: "16px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    backgroundColor: tokens.colorSurface,
    transitionProperty: "border-bottom-color",
    transitionDuration: tokens.transition,
    ":focus-within": {
      borderBottomColor: tokens.colorGreen,
    },
  },
  searchPrompt: {
    color: tokens.colorGreen,
    display: "inline-flex",
    flexShrink: 0,
  },
  searchInput: {
    flexGrow: 1,
    backgroundColor: "transparent",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.04em",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: 0,
    paddingRight: 0,
    outlineStyle: "none",
    "::placeholder": {
      color: tokens.colorTextMuted,
      fontStyle: "italic",
    },
  },
  searchCount: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
    flexShrink: 0,
  },
  searchClear: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  noMatches: {
    paddingTop: "40px",
    paddingBottom: "40px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
    textAlign: "center",
  },
  colHeader: {
    display: "grid",
    gridTemplateColumns: PROFILE_GRID_COLUMNS,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.18em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  rowsScroll: {
    flex: 1,
    overflowY: "auto",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  footerCta: {
    color: tokens.colorGreen,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
  },

  // Breadcrumb spans (a couple of color overrides)
  crumbDim: { color: tokens.colorTextDim },
  crumbBright: { color: tokens.colorText },

  // Empty state (gated on `?empty=1`)
  emptyRoot: {
    position: "relative",
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: "80px",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
    overflow: "hidden",
    backgroundImage:
      "radial-gradient(circle, rgba(255,255,255,0.045) 1px, transparent 1px)",
    backgroundSize: "28px 28px",
  },
  emptyWatermark: {
    position: "absolute",
    bottom: "-60px",
    right: "-60px",
    fontFamily: tokens.fontHead,
    fontSize: "340px",
    lineHeight: "1",
    letterSpacing: "-0.02em",
    color: "rgba(255,255,255,0.022)",
    pointerEvents: "none",
    userSelect: "none",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
  },
  emptyContent: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
  },
  emptyEyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
  },
  emptyHeadline: {
    display: "flex",
    flexDirection: "column",
    fontFamily: tokens.fontHead,
    fontSize: "96px",
    lineHeight: "0.9",
    letterSpacing: "0.01em",
    textTransform: "uppercase",
  },
  emptyHeadlineWhite: {
    color: tokens.colorText,
  },
  emptyHeadlineAccent: {
    color: tokens.colorGreen,
  },
  emptyRule: {
    width: "56px",
    height: "3px",
    backgroundColor: tokens.colorGreen,
    borderRadius: "2px",
  },
  emptyBody: {
    fontSize: "14px",
    lineHeight: "1.65",
    color: tokens.colorTextDim,
    maxWidth: "360px",
    margin: 0,
    fontFamily: tokens.fontBody,
  },
  emptyActions: {
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
    marginTop: "8px",
  },
  emptyCta: {
    color: tokens.colorGreen,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "3px",
    paddingLeft: 0,
    paddingRight: 0,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  emptyHint: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.12em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
  },
});
