import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useProfilesStyles = makeStyles({
  splitBody: {
    display: "grid",
    gridTemplateColumns: "1fr 0px 0px",
    height: "100%",
    transitionProperty: "grid-template-columns",
    transitionDuration: tokens.transitionSlow,
    transitionTimingFunction: "ease",
  },
  splitBodyOpen: {},
  isResizing: {
    transitionProperty: "none",
  },
  leftCol: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
  },
  resizeHandle: {
    backgroundColor: tokens.colorBorder,
    cursor: "col-resize",
    transitionProperty: "background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreen,
    },
  },
  hero: {
    height: "220px",
    position: "relative",
    overflow: "hidden",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  heroImg: {
    position: "absolute",
    inset: "0",
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "brightness(0.55)",
  },
  heroGradient: {
    position: "absolute",
    inset: "0",
    background: `linear-gradient(90deg, ${tokens.colorBg0} 0%, rgba(5,7,6,0.85) 30%, transparent 65%)`,
  },
  heroBody: {
    position: "absolute",
    inset: "0",
    paddingTop: "30px",
    paddingBottom: "30px",
    paddingLeft: "36px",
    paddingRight: "36px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    zIndex: 2,
  },
  greetingEyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
  },
  greeting: {
    fontFamily: tokens.fontHead,
    fontSize: "56px",
    lineHeight: "0.92",
    color: tokens.colorText,
    marginTop: "12px",
    letterSpacing: "-0.01em",
  },
  slideDots: {
    display: "flex",
    columnGap: "8px",
  },
  slideDot: {
    height: "3px",
    borderRadius: "2px",
    transitionProperty: "width, background-color",
    transitionDuration: tokens.transitionSlow,
  },
  slideDotActive: {
    width: "22px",
    backgroundColor: tokens.colorGreen,
  },
  slideDotInactive: {
    width: "6px",
    backgroundColor: tokens.colorTextFaint,
  },
  breadcrumb: {
    height: "38px",
    paddingLeft: "24px",
    paddingRight: "24px",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  breadcrumbScanning: {
    marginLeft: "auto",
    color: tokens.colorGreen,
  },
  colHeader: {
    display: "grid",
    gridTemplateColumns: "30px 1.3fr 0.7fr 0.6fr 80px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.18em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  rowsScroll: {
    flex: 1,
    overflowY: "auto",
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  footerCta: {
    color: tokens.colorGreen,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },
});
