import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useLogoCardStyles = makeStyles({
  card: {
    backgroundColor: tokens.colorSurface,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "4px",
    paddingTop: "32px",
    paddingBottom: "22px",
    paddingLeft: "28px",
    paddingRight: "28px",
    display: "flex",
    flexDirection: "column",
    minHeight: "360px",
    position: "relative",
    overflowX: "hidden",
    overflowY: "hidden",
  },
  cardHighlighted: {
    borderTopColor: tokens.colorGreen,
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    boxShadow: `0 0 0 3px ${tokens.colorGreenSoft}`,
  },
  code: {
    position: "absolute",
    top: "12px",
    left: "14px",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextFaint,
  },
  defaultBadge: {
    position: "absolute",
    top: "12px",
    right: "14px",
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.2em",
    color: tokens.colorGreen,
  },
  stage: {
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "28px",
    paddingBottom: "28px",
  },
  meta: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    paddingTop: "12px",
    marginTop: "12px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    columnGap: "16px",
  },
  metaLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextDim,
    letterSpacing: "0.06em",
  },
  metaNotes: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    textAlign: "right",
    maxWidth: "60%",
    lineHeight: "1.4",
  },
});
