import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useAppHeaderStyles = makeStyles({
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: `calc(${tokens.headerHeight} + 32px)`,
    paddingBottom: "32px",
    boxSizing: "border-box",
    zIndex: 10,
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    // Bottom 32px gradient fade-out; clicks fall through; grid cells re-enable for interactive parts.
    pointerEvents: "none",
  },
  headerBg: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: -1,
    pointerEvents: "none",
    backgroundImage: "linear-gradient(180deg, rgba(20,28,24,0.55) 0%, rgba(8,11,10,0.78) 100%)",
    backgroundColor: "rgba(8,11,10,0.62)",
    backdropFilter: "blur(20px) saturate(1.6)",
    WebkitBackdropFilter: "blur(20px) saturate(1.6)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.05), 0 6px 22px rgba(0,0,0,0.42)",
    maskImage: "linear-gradient(to bottom, #000 0%, #000 60%, transparent 100%)",
    WebkitMaskImage: "linear-gradient(to bottom, #000 0%, #000 60%, transparent 100%)",
  },

  brandCell: {
    display: "flex",
    alignItems: "center",
    paddingLeft: "24px",
    paddingRight: "24px",
    justifySelf: "start",
    pointerEvents: "auto",
  },
  brand: {
    display: "inline-flex",
    alignItems: "baseline",
    fontFamily: tokens.fontDisplay,
    fontSize: "34px",
    letterSpacing: "0.04em",
    lineHeight: "1",
    textDecorationLine: "none",
  },
  brandX: {
    color: tokens.colorGreen,
    textShadow: `0 0 12px ${tokens.colorGreenGlow}`,
  },
  brandWord: { color: tokens.colorText },

  navCell: {
    display: "flex",
    alignItems: "center",
    columnGap: "32px",
    justifySelf: "center",
    pointerEvents: "auto",
  },
  navLink: {
    fontFamily: tokens.fontNav,
    fontSize: "12px",
    letterSpacing: "0.04em",
    textTransform: "lowercase",
    color: tokens.colorTextDim,
    textDecorationLine: "none",
    paddingTop: "6px",
    paddingBottom: "6px",
    position: "relative",
    transitionProperty: "color, text-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
    "::after": {
      content: '""',
      position: "absolute",
      left: "0",
      right: "0",
      bottom: "-2px",
      height: "2px",
      backgroundColor: tokens.colorGreen,
      transform: "scaleX(0)",
      transformOrigin: "center",
      transitionProperty: "transform",
      transitionDuration: tokens.transition,
    },
  },
  navLinkActive: {
    color: tokens.colorGreen,
    textShadow: `0 0 10px ${tokens.colorGreenGlow}`,
    "::after": {
      transform: "scaleX(1)",
    },
  },

  actionsCell: {
    display: "flex",
    alignItems: "center",
    columnGap: "14px",
    paddingLeft: "24px",
    paddingRight: "24px",
    justifySelf: "end",
    pointerEvents: "auto",
  },

  scanBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "38px",
    height: "38px",
    backgroundColor: "transparent",
    backgroundImage: "none",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    cursor: "pointer",
    outlineStyle: "none",
    transitionProperty: "color, text-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorGreen,
      textShadow: `0 0 6px ${tokens.colorGreen}, 0 0 16px ${tokens.colorGreenGlow}`,
    },
  },
  scanIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  scanIconSpinning: {
    animationName: { to: { transform: "rotate(360deg)" } },
    animationDuration: "1.1s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },

  accountWrap: {
    position: "relative",
  },
  avatar: {
    width: "34px",
    height: "34px",
    borderRadius: "50%",
    backgroundImage: `linear-gradient(140deg, ${tokens.colorGreenDeep}, ${tokens.colorGreen})`,
    color: tokens.colorGreenInk,
    fontFamily: tokens.fontMono,
    fontWeight: 700,
    fontSize: "12px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    cursor: "pointer",
    outlineStyle: "none",
    transitionProperty: "transform, box-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      transform: "translateY(-1px)",
      boxShadow: `0 4px 14px ${tokens.colorGreenSoft}`,
    },
  },
  avatarOpen: {
    boxShadow: `0 0 0 2px ${tokens.colorGreen}, 0 6px 18px ${tokens.colorGreenSoft}`,
  },
});
