import { makeStyles } from "@griffel/react";

import { tokens } from "../../styles/tokens.js";

export const useSidebarStyles = makeStyles({
  root: {
    gridArea: "sidebar",
    backgroundColor: "#090909",
    borderRight: `1px solid ${tokens.colorBorder}`,
    display: "flex",
    flexDirection: "column",
    position: "sticky",
    top: tokens.headerHeight,
    height: `calc(100vh - ${tokens.headerHeight})`,
    overflow: "hidden",
    zIndex: 50,
    transitionProperty: "width",
    transitionDuration: "0.22s",
    transitionTimingFunction: "ease",
    width: tokens.sidebarWidth,
    flexShrink: "0",
  },
  rootCollapsed: {
    width: tokens.sidebarCollapsedWidth,
    overflow: "visible",
  },

  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "0",
    paddingLeft: tokens.space4,
    paddingRight: tokens.space4,
    height: "52px",
    fontSize: "13px",
    color: tokens.colorMuted,
    borderLeft: "2px solid transparent",
    transitionProperty: "background, border-color",
    transitionDuration: tokens.transition,
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
    textDecoration: "none",
    "--label-color": tokens.colorMuted,
    "--icon-opacity": "0.07",
    ":hover": {
      backgroundColor: "rgba(255,255,255,0.03)",
      "--label-color": tokens.colorOffWhite,
      "--icon-opacity": "0.13",
    },
  },
  navItemActive: {
    backgroundColor: tokens.colorRedDim,
    borderLeftColor: tokens.colorRed,
    "--label-color": tokens.colorWhite,
    "--icon-opacity": "0.20",
  },
  navItemCollapsed: {
    paddingLeft: "0",
    paddingRight: "0",
    justifyContent: "center",
    borderLeftWidth: "0",
    height: "44px",
    overflow: "visible",
    ":hover": { backgroundColor: "rgba(255,255,255,0.03)" },
  },
  navItemCollapsedActive: {
    backgroundColor: tokens.colorRedDim,
    borderLeft: `2px solid ${tokens.colorRed}`,
  },

  navLabel: {
    fontFamily: tokens.fontHead,
    fontSize: "15px",
    letterSpacing: "0.08em",
    color: "var(--label-color)",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    position: "relative",
    zIndex: 1,
    whiteSpace: "nowrap",
  },
  navLabelHidden: { display: "none" },

  navCardIcon: {
    position: "absolute",
    right: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    width: "40px",
    height: "40px",
    opacity: "var(--icon-opacity)",
    color: tokens.colorWhite,
    pointerEvents: "none",
    flexShrink: "0",
    transitionProperty: "opacity",
    transitionDuration: tokens.transition,
  },
  navCardIconCollapsed: {
    position: "static",
    transform: "none",
    width: "18px",
    height: "18px",
    opacity: "0.5",
    color: tokens.colorMuted,
  },

  navSideTip: {
    position: "absolute",
    left: "calc(100% + 10px)",
    top: "50%",
    transform: "translateY(-50%) translateX(-4px)",
    whiteSpace: "nowrap",
    fontSize: "10px",
    fontFamily: tokens.fontBody,
    letterSpacing: "0.04em",
    fontWeight: "500",
    background: "#1a1a1a",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "rgba(255,255,255,0.5)",
    padding: "3px 8px",
    borderRadius: "3px",
    pointerEvents: "none",
    opacity: "0",
    transitionProperty: "opacity, transform",
    transitionDuration: "0.12s",
    transitionTimingFunction: "ease",
    zIndex: "9999",
  },
  navSideTipVisible: {
    opacity: "1",
    transform: "translateY(-50%) translateX(0)",
  },
  navSideTipHidden: { display: "none" },

  navSpacer: { flex: "1" },

  collapseBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: tokens.space2,
    paddingLeft: tokens.space4,
    paddingRight: tokens.space4,
    height: "44px",
    border: "none",
    borderTop: `1px solid ${tokens.colorBorder}`,
    background: "transparent",
    color: tokens.colorMuted2,
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%",
    whiteSpace: "nowrap",
    flexShrink: "0",
    transitionProperty: "color, background",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorMuted,
      backgroundColor: "rgba(255,255,255,0.02)",
    },
  },
  collapseBtnCollapsed: { justifyContent: "center", paddingLeft: "0", paddingRight: "0" },
  collapseBtnIcon: {
    width: "15px",
    height: "15px",
    flexShrink: "0",
    transitionProperty: "transform",
    transitionDuration: "0.22s",
    transitionTimingFunction: "ease",
  },
  collapseBtnIconRotated: { transform: "rotate(180deg)" },

  userWrap: { position: "relative", flexShrink: "0" },
  userBtn: {
    display: "flex",
    alignItems: "center",
    gap: tokens.space2,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: tokens.space4,
    paddingRight: tokens.space4,
    width: "100%",
    background: "none",
    border: "none",
    borderTop: `1px solid ${tokens.colorBorder}`,
    cursor: "pointer",
    textAlign: "left",
    color: "inherit",
    fontFamily: tokens.fontBody,
    transitionProperty: "background",
    transitionDuration: tokens.transition,
    ":hover": { backgroundColor: "rgba(255,255,255,0.04)" },
  },
  userBtnMenuOpen: { backgroundColor: "rgba(255,255,255,0.05)" },
  userBtnCollapsed: { justifyContent: "center", paddingLeft: "0", paddingRight: "0" },
  avatar: {
    width: "30px",
    height: "30px",
    borderRadius: tokens.radiusFull,
    backgroundColor: tokens.colorRedDim,
    border: `1px solid ${tokens.colorRedBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: "700",
    color: tokens.colorRed,
    flexShrink: "0",
  },
  userText: { flex: "1", minWidth: "0" },
  userName: { fontSize: "13px", fontWeight: "600", color: tokens.colorWhite, lineHeight: "1.3", whiteSpace: "nowrap" },
  userSub:  { fontSize: "10px", color: tokens.colorMuted, whiteSpace: "nowrap" },
  userChevron: {
    color: tokens.colorMuted2,
    flexShrink: "0",
    transitionProperty: "transform, color",
    transitionDuration: "0.15s",
  },
  userChevronOpen: { transform: "rotate(90deg)", color: tokens.colorMuted },

  // ── Profile menu ─────────────────────────────────────────────────────────
  profileMenu: {
    position: "absolute",
    bottom: "calc(100% + 4px)",
    left: "8px",
    right: "8px",
    backgroundColor: tokens.colorSurface,
    border: `1px solid ${tokens.colorBorder2}`,
    borderRadius: tokens.radiusMd,
    boxShadow: "0 -8px 32px rgba(0,0,0,0.5), 0 2px 8px rgba(0,0,0,0.4)",
    zIndex: "200",
    overflow: "hidden",
  },
  profileMenuCollapsed: { left: "52px", right: "auto", width: "220px", bottom: "8px" },
  pmUserHead: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 14px",
    borderBottom: `1px solid ${tokens.colorBorder}`,
    backgroundColor: tokens.colorSurface2,
  },
  pmAvatar: {
    width: "32px", height: "32px", borderRadius: "50%",
    backgroundColor: tokens.colorRed,
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: "13px", fontWeight: "700", color: tokens.colorWhite, flexShrink: "0",
  },
  pmUserInfo: { minWidth: "0" },
  pmUserName: { fontSize: "12px", fontWeight: "600", color: tokens.colorWhite, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  pmUserEmail: { fontSize: "10px", color: tokens.colorMuted2, marginTop: "1px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  pmSectionLabel: {
    padding: "8px 14px 4px",
    fontSize: "9px", fontWeight: "700", letterSpacing: "0.12em",
    textTransform: "uppercase", color: tokens.colorMuted2,
  },
  pmItem: {
    display: "flex", alignItems: "center", gap: "8px",
    width: "100%", padding: "7px 14px",
    background: "none", border: "none", cursor: "pointer",
    fontFamily: tokens.fontBody, fontSize: "12px", color: tokens.colorMuted, textAlign: "left",
    transitionProperty: "background, color", transitionDuration: tokens.transition,
    ":hover": { backgroundColor: "rgba(255,255,255,0.05)", color: tokens.colorWhite },
  },
  pmItemDanger: {
    color: "rgba(206,17,38,0.7)",
    ":hover": { backgroundColor: "rgba(206,17,38,0.08)", color: tokens.colorRed },
  },
  pmItemName: { flex: "1" },
  pmItemCount: { fontSize: "10px", color: tokens.colorMuted2, flexShrink: "0" },
  pmItemDot: { width: "6px", height: "6px", borderRadius: "50%", backgroundColor: tokens.colorMuted2, flexShrink: "0" },
  pmDivider: { height: "1px", backgroundColor: tokens.colorBorder, margin: "4px 0" },

  // ── Sign-out dialog ───────────────────────────────────────────────────────
  dialogOverlay: {
    position: "fixed", inset: "0", zIndex: "9000",
    backgroundColor: "rgba(0,0,0,0.7)", backdropFilter: "blur(4px)",
    display: "flex", alignItems: "center", justifyContent: "center",
  },
  dialog: {
    backgroundColor: tokens.colorSurface, border: `1px solid ${tokens.colorBorder2}`,
    borderRadius: tokens.radiusLg, boxShadow: "0 24px 64px rgba(0,0,0,0.7)",
    padding: "28px 28px 24px", width: "360px", maxWidth: "calc(100vw - 32px)",
    display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", textAlign: "center",
  },
  dialogIcon: {
    width: "44px", height: "44px", borderRadius: "50%",
    backgroundColor: "rgba(206,17,38,0.1)", border: "1px solid rgba(206,17,38,0.25)",
    display: "flex", alignItems: "center", justifyContent: "center",
    color: tokens.colorRed, marginBottom: "4px",
  },
  dialogTitle: { fontFamily: tokens.fontHead, fontSize: "20px", letterSpacing: "0.06em", color: tokens.colorWhite, textTransform: "uppercase" },
  dialogBody: { fontSize: "13px", color: tokens.colorMuted, lineHeight: "1.6", maxWidth: "280px" },
  dialogActions: { display: "flex", gap: "10px", marginTop: "8px" },
  btnGhost: {
    display: "inline-flex", alignItems: "center", gap: "6px", padding: "7px 16px",
    backgroundColor: "transparent", border: `1px solid ${tokens.colorBorder2}`,
    borderRadius: tokens.radiusSm, color: tokens.colorMuted, fontSize: "12px", fontWeight: "600",
    cursor: "pointer", fontFamily: tokens.fontBody,
    transitionProperty: "background, color", transitionDuration: tokens.transition,
    ":hover": { backgroundColor: tokens.colorSurface2, color: tokens.colorWhite },
  },
  btnDanger: {
    display: "inline-flex", alignItems: "center", gap: "6px", padding: "7px 16px",
    backgroundColor: tokens.colorRed, border: `1px solid ${tokens.colorRed}`,
    borderRadius: tokens.radiusSm, color: tokens.colorWhite, fontSize: "12px", fontWeight: "700",
    cursor: "pointer", fontFamily: tokens.fontBody,
    transitionProperty: "background", transitionDuration: tokens.transition,
    ":hover": { backgroundColor: tokens.colorRedDark },
  },
});
