import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";
import { PROFILE_GRID_COLUMNS } from "../../pages/Profiles/grid.js";

export const useFilmRowStyles = makeStyles({
  row: {
    display: "grid",
    gridTemplateColumns: PROFILE_GRID_COLUMNS,
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    alignItems: "center",
    backgroundColor: "transparent",
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: "transparent",
    cursor: "pointer",
    transitionProperty: "background-color, border-left-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(232, 238, 232, 0.05)",
      borderLeftColor: tokens.colorBorder,
    },
  },
  rowSelected: {
    backgroundColor: tokens.colorGreenSoft,
    borderLeftColor: tokens.colorGreen,
    ":hover": {
      backgroundColor: tokens.colorGreenSoft,
      borderLeftColor: tokens.colorGreen,
    },
  },
  thumbBtn: {
    position: "relative",
    width: "26px",
    height: "38px",
    padding: 0,
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    display: "block",
    overflow: "hidden",
    borderRadius: "1px",
    transitionProperty: "transform, box-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      transform: "scale(1.05)",
      boxShadow: `0 0 0 1px ${tokens.colorGreen}, 0 4px 12px rgba(0,0,0,0.45)`,
    },
    ":hover > span": {
      opacity: 1,
    },
  },
  thumb: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    display: "block",
  },
  thumbHover: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    color: tokens.colorGreen,
    backgroundColor: "rgba(5, 7, 6, 0.55)",
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: tokens.transition,
    pointerEvents: "none",
  },
  title: { fontSize: "12px", color: tokens.colorText },
  year: { color: tokens.colorTextMuted },
  meta: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    marginTop: "2px",
  },
  chipRow: { display: "flex", columnGap: "4px" },
  chipSmall: {
    fontSize: "9px",
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: "5px",
    paddingRight: "5px",
  },
  ratingCell: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextDim,
    display: "flex",
    alignItems: "center",
    columnGap: "4px",
  },
  ratingValue: { color: tokens.colorYellow },
  editCell: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  editAction: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: "rgba(232, 238, 232, 0.35)",
    textDecorationThickness: "1px",
    textUnderlineOffset: "3px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorGreen,
      textDecorationColor: tokens.colorGreen,
    },
  },
});
