import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useFilterSlideStyles = makeStyles({
  panel: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    fontFamily: tokens.fontMono,
    color: tokens.colorText,
    paddingTop: "12px",
  },
  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
  },
  eyebrowAccent: {
    color: tokens.colorText,
  },

  table: {
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    paddingRight: "16px",
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderLeftColor: tokens.colorBorder,
    backgroundColor: "rgba(20, 24, 22, 0.55)",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "120px 1fr",
    columnGap: "16px",
    alignItems: "center",
  },
  rowLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
  },
  rowOptions: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: "16px",
    rowGap: "6px",
  },
  toggle: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    letterSpacing: "0.04em",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
  },
  toggleOn: {
    color: tokens.colorGreen,
    ":hover": {
      color: tokens.colorGreen,
    },
  },
  toggleBox: {
    fontFamily: tokens.fontMono,
    color: "inherit",
  },

  actions: {
    marginTop: "auto",
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
    paddingTop: "16px",
    flexWrap: "wrap",
  },
  primary: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "3px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  secondary: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "3px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: "rgba(232, 238, 232, 0.25)",
    textDecorationThickness: "1px",
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color, opacity",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
    ":disabled": {
      opacity: 0.35,
      cursor: "not-allowed",
    },
  },
  hint: {
    marginLeft: "auto",
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.12em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
  },
});
