import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useProfileFormStyles = makeStyles({
  shell: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    // Include AppHeader's decorative 32px gradient fade-out to avoid overlap.
    paddingTop: `calc(${tokens.headerHeight} + 32px)`,
    boxSizing: "border-box",
    overflowY: "auto",
  },
  breadcrumb: {
    height: "38px",
    paddingLeft: "24px",
    paddingRight: "24px",
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
  crumbDim: { color: tokens.colorTextDim },
  crumbBright: { color: tokens.colorText },
  crumbSpacer: { marginLeft: "auto" },

  page: {
    flexGrow: 1,
    display: "flex",
    justifyContent: "center",
    paddingTop: "56px",
    paddingBottom: "56px",
    paddingLeft: "24px",
    paddingRight: "24px",
  },
  card: {
    width: "100%",
    maxWidth: "560px",
    display: "flex",
    flexDirection: "column",
    rowGap: "28px",
  },

  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
  },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "56px",
    lineHeight: "1",
    color: tokens.colorText,
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
  subtitle: {
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    color: tokens.colorTextMuted,
    lineHeight: "1.55",
    maxWidth: "440px",
  },

  divider: {
    height: "1px",
    backgroundColor: tokens.colorBorderSoft,
  },

  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    rowGap: "8px",
  },
  label: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.22em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "transparent",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: 0,
    paddingRight: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
    transitionProperty: "border-bottom-color",
    transitionDuration: tokens.transition,
    ":focus": {
      outlineStyle: "none",
      borderBottomColor: tokens.colorGreen,
    },
    "::placeholder": {
      color: tokens.colorTextFaint,
    },
  },
  pathSection: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    rowGap: "8px",
  },
  pathRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },
  pathInput: {
    flexGrow: 1,
  },
  browserFloat: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    marginTop: "6px",
    zIndex: 20,
  },
  browseBtn: {
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    columnGap: "6px",
    transitionProperty: "color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorGreen,
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
    },
  },
  browseBtnActive: {
    color: tokens.colorGreenInk,
    backgroundColor: tokens.colorGreen,
    borderTopColor: tokens.colorGreen,
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    ":hover": {
      color: tokens.colorGreenInk,
      backgroundColor: tokens.colorGreen,
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
    },
  },

  segment: {
    display: "flex",
    columnGap: 0,
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    width: "fit-content",
    overflow: "hidden",
  },
  segmentBtn: {
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    paddingRight: "16px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    cursor: "pointer",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
  },
  segmentBtnActive: {
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    ":hover": {
      color: tokens.colorGreenInk,
    },
  },
  segmentHint: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextFaint,
    letterSpacing: "0.04em",
    lineHeight: "1.55",
    maxWidth: "440px",
  },

  extChips: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: "6px",
    rowGap: "6px",
  },
  extChip: {
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.06em",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "10px",
    paddingRight: "10px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusFull,
    cursor: "pointer",
    transitionProperty: "color, border-color, background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
  },
  extChipActive: {
    color: tokens.colorGreen,
    borderTopColor: tokens.colorGreen,
    borderRightColor: tokens.colorGreen,
    borderBottomColor: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
    backgroundColor: tokens.colorGreenSoft,
    ":hover": {
      color: tokens.colorGreen,
    },
  },

  errorMsg: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorRed,
    letterSpacing: "0.04em",
  },

  footer: {
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    paddingTop: "16px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
  },
  footerSpacer: { flexGrow: 1 },
  textAction: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "2px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "none",
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  textActionAccent: {
    color: tokens.colorGreen,
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "4px",
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  textActionDanger: {
    color: tokens.colorRed,
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorRed,
    textDecorationThickness: "1px",
    textUnderlineOffset: "4px",
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },

  deleteConfirm: {
    display: "flex",
    flexDirection: "column",
    rowGap: "12px",
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "16px",
    paddingRight: "16px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorRed,
    borderRightColor: tokens.colorRed,
    borderBottomColor: tokens.colorRed,
    borderLeftColor: tokens.colorRed,
    borderRadius: tokens.radiusSm,
    backgroundColor: "rgba(255, 93, 108, 0.06)",
  },
  deleteConfirmMsg: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorText,
    letterSpacing: "0.04em",
  },
  deleteConfirmRow: {
    display: "flex",
    columnGap: "16px",
  },
});
