import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useLibraryStyles = makeStyles({
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflowX: "hidden",
    overflowY: "auto",
    backgroundColor: tokens.colorBg0,
    paddingLeft: "40px",
    paddingRight: "40px",
  },

  hero: {
    flexShrink: 0,
    height: "75vh",
    position: "relative",
    overflow: "hidden",
    borderRadius: "6px",
  },
  heroActive: {
    backgroundColor: tokens.colorBg0,
    borderRadius: 0,
    overflow: "visible",
  },
  heroPanelBg: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: tokens.colorBg0,
    backgroundImage: `radial-gradient(circle at 70% 35%, rgba(120, 200, 150, 0.07) 0%, transparent 55%), radial-gradient(circle, rgba(255,255,255,0.045) 1px, transparent 1px)`,
    backgroundSize: "100% 100%, 28px 28px",
    pointerEvents: "none",
    maskImage: "radial-gradient(ellipse 92% 88% at 50% 48%, #000 55%, transparent 100%)",
    WebkitMaskImage: "radial-gradient(ellipse 92% 88% at 50% 48%, #000 55%, transparent 100%)",
  },
  heroBody: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    paddingTop: `calc(${tokens.headerHeight} + 32px)`,
    paddingBottom: "20px",
    paddingLeft: "44px",
    paddingRight: "44px",
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    zIndex: 2,
  },
  greetingEyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
  },
  greeting: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.92",
    color: tokens.colorText,
    marginTop: "28px",
    letterSpacing: "-0.02em",
  },

  searchBar: {
    position: "absolute",
    top: `calc(${tokens.headerHeight} + 24px)`,
    right: "32px",
    zIndex: 3,
    width: "320px",
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    paddingRight: "12px",
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.42) 22%, rgba(20,28,24,0.42) 78%, rgba(20,28,24,0) 100%)",
    transitionProperty: "background-image",
    transitionDuration: tokens.transition,
  },
  searchBarFocused: {
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.7) 22%, rgba(20,28,24,0.7) 78%, rgba(20,28,24,0) 100%)",
  },
  searchIcon: {
    color: tokens.colorGreen,
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
  },
  searchInputWrap: {
    position: "relative",
    flexGrow: 1,
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    height: "20px",
  },
  searchInput: {
    width: "100%",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    outlineStyle: "none",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.06em",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: "12px",
    "::placeholder": {
      color: tokens.colorTextMuted,
      letterSpacing: "0.14em",
      textTransform: "uppercase",
      fontSize: "10px",
    },
  },
  searchClear: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },

  noResults: {
    paddingTop: "40px",
    paddingBottom: "40px",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
    textAlign: "center",
  },
  searchResults: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
  },
  searchGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, 200px)",
    justifyContent: "start",
    columnGap: "16px",
    rowGap: "24px",
  },

  rowsScroll: {
    flexGrow: 1,
    marginTop: "-32vh",
    position: "relative",
    zIndex: 2,
    paddingTop: "20px",
    paddingBottom: "60px",
    display: "flex",
    flexDirection: "column",
    rowGap: "28px",
  },
  rowHeader: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorTextDim,
  },

  emptyHero: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    paddingTop: `calc(${tokens.headerHeight} + 64px)`,
    paddingBottom: "60px",
    paddingLeft: "60px",
    paddingRight: "60px",
    maxWidth: "640px",
  },
  emptyBody: {
    fontSize: "15px",
    lineHeight: "1.55",
    color: tokens.colorTextDim,
    maxWidth: "560px",
  },
  emptyCta: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "10px",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.12)",
    color: "#fff",
    paddingTop: "14px",
    paddingBottom: "14px",
    paddingLeft: "26px",
    paddingRight: "30px",
    borderRadius: "999px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "rgba(255,255,255,0.30)",
    borderRightColor: "rgba(255,255,255,0.18)",
    borderBottomColor: "rgba(255,255,255,0.10)",
    borderLeftColor: "rgba(255,255,255,0.18)",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    fontWeight: 600,
    textDecorationLine: "none",
    cursor: "pointer",
    backdropFilter: "blur(20px) saturate(180%)",
    WebkitBackdropFilter: "blur(20px) saturate(180%)",
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.35), inset 0 -1px 0 rgba(0,0,0,0.20), 0 10px 32px rgba(0,0,0,0.45)",
    transitionProperty: "transform, color, border-color, background-color",
    transitionDuration: "0.18s",
    transitionTimingFunction: "ease-out",
    ":hover": {
      transform: "translateY(-1px)",
      backgroundColor: "oklch(0.78 0.20 150 / 0.14)",
      borderTopColor: "oklch(0.78 0.20 150 / 0.40)",
      borderRightColor: "oklch(0.78 0.20 150 / 0.28)",
      borderBottomColor: "oklch(0.78 0.20 150 / 0.18)",
      borderLeftColor: "oklch(0.78 0.20 150 / 0.28)",
      color: tokens.colorGreen,
    },
    ":active": {
      transform: "translateY(0) scale(0.98)",
    },
  },
});
