import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useGoodbyeStyles = makeStyles({
  shell: {
    width: "100vw",
    height: "100vh",
    backgroundColor: tokens.colorBg0,
    position: "relative",
    overflowX: "hidden",
    overflowY: "hidden",
    color: tokens.colorText,
  },
  grain: { opacity: 0.22 },
  glow: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    background: `radial-gradient(ellipse at center, ${tokens.colorGreenSoft} 0%, transparent 55%)`,
    pointerEvents: "none",
  },
  watermark: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: tokens.fontHead,
    fontSize: "30vw",
    color: tokens.colorText,
    opacity: 0.03,
    letterSpacing: "-0.04em",
    pointerEvents: "none",
    userSelect: "none",
  },
  content: {
    position: "relative",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    rowGap: "18px",
    padding: "24px",
    textAlign: "center",
    zIndex: 2,
  },
  logoWrap: { opacity: 0.6 },
  eyebrow: { color: tokens.colorGreen },
  title: {
    fontFamily: tokens.fontHead,
    fontSize: "64px",
    lineHeight: "0.95",
    letterSpacing: "-0.01em",
    textTransform: "uppercase",
  },
  subtitle: { color: tokens.colorTextDim, maxWidth: "460px" },
  actions: {
    display: "flex",
    alignItems: "center",
    columnGap: "16px",
    marginTop: "12px",
  },
  primaryBtn: {
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "22px",
    paddingRight: "22px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    fontWeight: 700,
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
  },
  countdown: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    color: tokens.colorTextMuted,
    letterSpacing: "0.1em",
  },
});
