import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useDashboardStyles = makeStyles({
  pageRoot: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflow: "hidden",
  },
  splitBody: {
    display: "grid",
    gridTemplateColumns: "1fr 0px 0px",
    flex: "1",
    minHeight: "0",
    transitionProperty: "grid-template-columns",
    transitionDuration: "0.25s",
    transitionTimingFunction: "ease",
    overflow: "hidden",
  },
  resizeHandle: {
    width: "4px",
    cursor: "col-resize",
    backgroundColor: tokens.colorBorder,
    transitionProperty: "background-color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorRed,
    },
  },
  splitLeft: {
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    minWidth: "0",
  },
  rightPane: {
    borderLeft: `1px solid ${tokens.colorBorder}`,
    backgroundColor: tokens.colorSurface,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: "0",
    minHeight: "0",
  },
  // ── Empty state ───────────────────────────────────────────────────────────
  emptyRoot: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: "80px",
    height: "100%",
    overflow: "hidden",
    // Subtle dot-grid texture
    backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.055) 1px, transparent 1px)",
    backgroundSize: "28px 28px",
  },
  emptyWatermark: {
    position: "absolute",
    bottom: "-60px",
    right: "-60px",
    fontFamily: tokens.fontHead,
    fontSize: "340px",
    lineHeight: "1",
    letterSpacing: "-0.02em",
    color: "rgba(255,255,255,0.022)",
    pointerEvents: "none",
    userSelect: "none",
    whiteSpace: "nowrap",
  },
  emptyContent: {
    position: "relative",
    zIndex: "1",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  emptyHeadline: {
    display: "flex",
    flexDirection: "column",
    fontFamily: tokens.fontHead,
    fontSize: "96px",
    lineHeight: "0.9",
    letterSpacing: "0.01em",
  },
  emptyHeadlineWhite: {
    color: tokens.colorOffWhite,
  },
  emptyHeadlineRed: {
    color: tokens.colorRed,
  },
  emptyRule: {
    width: "56px",
    height: "3px",
    backgroundColor: tokens.colorRed,
    borderRadius: "2px",
  },
  emptyBody: {
    fontSize: "14px",
    lineHeight: "1.65",
    color: "rgba(255,255,255,0.42)",
    maxWidth: "320px",
    margin: "0",
    fontFamily: tokens.fontBody,
  },
  emptyBtn: {
    alignSelf: "flex-start",
    marginTop: "4px",
    padding: "12px 28px",
    borderRadius: tokens.radiusSm,
    border: "none",
    backgroundColor: tokens.colorRed,
    color: "#fff",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    fontFamily: tokens.fontBody,
    transitionProperty: "opacity, transform",
    transitionDuration: tokens.transition,
    ":hover": {
      opacity: "0.85",
      transform: "translateY(-1px)",
    },
    ":active": {
      transform: "translateY(0)",
      opacity: "1",
    },
  },
});
