import { makeStyles } from "@griffel/react";

import { PROFILE_GRID_COLUMNS } from "~/pages/profiles-page/grid";
import { tokens } from "~/styles/tokens";

export const useProfilesExplorerStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
    height: "100%",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "24px",
    paddingRight: "16px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
    backgroundColor: tokens.colorSurface,
    transitionProperty: "border-bottom-color",
    transitionDuration: tokens.transition,
    ":focus-within": {
      borderBottomColor: tokens.colorGreen,
    },
  },
  searchPrompt: {
    color: tokens.colorGreen,
    display: "inline-flex",
    flexShrink: 0,
  },
  searchInput: {
    flexGrow: 1,
    backgroundColor: "transparent",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.04em",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: 0,
    paddingRight: 0,
    outlineStyle: "none",
    "::placeholder": {
      color: tokens.colorTextMuted,
      fontStyle: "italic",
    },
  },
  searchCount: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
    flexShrink: 0,
  },
  searchClear: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextMuted,
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  noMatches: {
    paddingTop: "40px",
    paddingBottom: "40px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
    textAlign: "center",
  },
  colHeader: {
    display: "grid",
    gridTemplateColumns: PROFILE_GRID_COLUMNS,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "24px",
    paddingRight: "24px",
    columnGap: "16px",
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.18em",
    color: tokens.colorTextFaint,
    textTransform: "uppercase",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorderSoft,
  },
  rowsScroll: {
    flexGrow: 1,
    overflowY: "auto",
  },
});
