import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useSearchSlideStyles = makeStyles({
  panel: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    fontFamily: tokens.fontMono,
    color: tokens.colorText,
    paddingTop: "12px",
  },
  eyebrow: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    color: tokens.colorGreen,
    textTransform: "uppercase",
  },
  eyebrowAccent: {
    color: tokens.colorText,
  },
  promptRow: {
    display: "flex",
    alignItems: "baseline",
    columnGap: "16px",
    fontFamily: tokens.fontMono,
    fontSize: "56px",
    color: tokens.colorText,
    lineHeight: "1",
    letterSpacing: "-0.01em",
  },
  promptCaret: {
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
  },
  promptText: {
    color: tokens.colorText,
    display: "inline-flex",
    alignItems: "center",
    columnGap: "4px",
    minHeight: "1em",
    overflowX: "hidden",
    whiteSpace: "nowrap",
  },
  promptCursor: {
    display: "inline-block",
    width: "12px",
    height: "0.85em",
    backgroundColor: tokens.colorGreen,
    boxShadow: `0 0 6px ${tokens.colorGreen}, 0 0 14px ${tokens.colorGreenGlow}`,
    animationName: {
      "0%, 100%": { opacity: "1", transform: "scaleY(1)" },
      "50%": { opacity: "0.25", transform: "scaleY(0.86)" },
    },
    animationDuration: "1.05s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  status: {
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.06em",
    color: tokens.colorTextDim,
    display: "flex",
    flexWrap: "wrap",
    columnGap: "10px",
    rowGap: "6px",
    alignItems: "center",
  },
  statusSep: {
    color: tokens.colorTextFaint,
  },
  statusAccent: {
    color: tokens.colorGreen,
  },
  statusHint: {
    color: tokens.colorTextMuted,
    fontStyle: "italic",
  },
  actions: {
    marginTop: "auto",
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
    paddingTop: "16px",
    flexWrap: "wrap",
  },
  primary: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "3px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorGreen,
    fontFamily: tokens.fontMono,
    fontSize: "13px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: tokens.colorGreen,
    textDecorationThickness: "1px",
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
  },
  secondary: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    paddingTop: 0,
    paddingBottom: "3px",
    paddingLeft: 0,
    paddingRight: 0,
    color: tokens.colorTextDim,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    textDecorationColor: "rgba(232, 238, 232, 0.25)",
    textDecorationThickness: "1px",
    textUnderlineOffset: "5px",
    cursor: "pointer",
    transitionProperty: "color, text-decoration-color, opacity",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
      textDecorationColor: tokens.colorText,
    },
    ":disabled": {
      opacity: 0.35,
      cursor: "not-allowed",
    },
  },
});
