import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const usePosterRowStyles = makeStyles({
  row: {
    display: "flex",
    flexDirection: "column",
    rowGap: "12px",
  },
  header: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorTextDim,
  },
  frame: {
    position: "relative",
  },
  track: {
    display: "flex",
    columnGap: "16px",
    overflowX: "auto",
    overflowY: "hidden",
    scrollSnapType: "x proximity",
    "::-webkit-scrollbar": { display: "none" },
    msOverflowStyle: "none",
    scrollbarWidth: "none",
    paddingBottom: "8px",
  },
  arrow: {
    position: "absolute",
    top: "calc(50% - 24px)",
    width: "44px",
    height: "44px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(8,11,10,0.65)",
    backdropFilter: "blur(10px) saturate(1.4)",
    WebkitBackdropFilter: "blur(10px) saturate(1.4)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: "50%",
    color: tokens.colorText,
    cursor: "pointer",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    zIndex: 4,
    transitionProperty: "background-color, border-color, color, transform",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(8,11,10,0.85)",
      borderTopColor: tokens.colorGreen,
      borderRightColor: tokens.colorGreen,
      borderBottomColor: tokens.colorGreen,
      borderLeftColor: tokens.colorGreen,
      color: tokens.colorGreen,
      transform: "scale(1.06)",
    },
  },
  arrowLeft: {
    left: "-12px",
  },
  arrowRight: {
    right: "-12px",
  },
});
