import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useAuthFormStyles = makeStyles({
  form: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    rowGap: "6px",
  },
  label: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
  },
  input: {
    width: "100%",
    height: "40px",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: "12px",
    paddingRight: "12px",
    backgroundColor: "rgba(5, 7, 6, 0.6)",
    color: tokens.colorText,
    fontFamily: tokens.fontBody,
    fontSize: "14px",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderRadius: tokens.radiusSm,
    outlineStyle: "none",
    transitionProperty: "border-color, box-shadow",
    transitionDuration: tokens.transition,
    "::placeholder": { color: tokens.colorTextFaint },
    ":hover": {
      borderTopColor: tokens.colorTextFaint,
      borderRightColor: tokens.colorTextFaint,
      borderBottomColor: tokens.colorTextFaint,
      borderLeftColor: tokens.colorTextFaint,
    },
    ":focus": {
      borderTopColor: tokens.colorGreenDeep,
      borderRightColor: tokens.colorGreenDeep,
      borderBottomColor: tokens.colorGreenDeep,
      borderLeftColor: tokens.colorGreenDeep,
      boxShadow: `0 0 0 3px ${tokens.colorGreenSoft}`,
    },
  },
  inputError: {
    borderTopColor: tokens.colorRed,
    borderRightColor: tokens.colorRed,
    borderBottomColor: tokens.colorRed,
    borderLeftColor: tokens.colorRed,
  },
  fieldError: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: tokens.colorRed,
  },
  primaryBtn: {
    marginTop: "8px",
    width: "100%",
    height: "44px",
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    fontWeight: 700,
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
    transitionProperty: "background-color, transform, box-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreenDeep,
      color: tokens.colorText,
      boxShadow: `0 0 24px ${tokens.colorGreenSoft}`,
    },
    ":active": { transform: "translateY(1px)" },
    ":focus-visible": { boxShadow: `0 0 0 3px ${tokens.colorGreenSoft}` },
  },
  helpRow: {
    marginTop: "20px",
    paddingTop: "20px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    fontFamily: tokens.fontBody,
    fontSize: "12px",
    color: tokens.colorTextDim,
  },
  textLink: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
    textDecorationLine: "none",
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  inlineLink: {
    color: tokens.colorGreen,
    textDecorationLine: "none",
    fontWeight: 600,
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
});
