import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens.js";

export const useAuthFormStyles = makeStyles({
  form: {
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    rowGap: "8px",
  },
  label: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
  },
  input: {
    width: "100%",
    height: "32px",
    paddingTop: 0,
    paddingBottom: "6px",
    paddingLeft: 0,
    paddingRight: 0,
    backgroundColor: "transparent",
    color: tokens.colorText,
    fontFamily: tokens.fontBody,
    fontSize: "14px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
    borderRadius: 0,
    outlineStyle: "none",
    transitionProperty: "border-color",
    transitionDuration: tokens.transition,
    "::placeholder": {
      color: tokens.colorTextFaint,
      fontFamily: tokens.fontBody,
      fontSize: "14px",
    },
    ":hover": { borderBottomColor: tokens.colorTextFaint },
    ":focus": { borderBottomColor: tokens.colorGreen },
  },
  inputError: {
    borderBottomColor: tokens.colorRed,
  },
  fieldError: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: tokens.colorRed,
  },
  primaryBtn: {
    marginTop: "8px",
    width: "100%",
    height: "44px",
    backgroundColor: tokens.colorGreen,
    color: tokens.colorGreenInk,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    fontWeight: 700,
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
    transitionProperty: "background-color, transform, box-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreenDeep,
      color: tokens.colorText,
      boxShadow: `0 0 24px ${tokens.colorGreenSoft}`,
    },
    ":active": { transform: "translateY(1px)" },
    ":focus-visible": { boxShadow: `0 0 0 3px ${tokens.colorGreenSoft}` },
  },
  helpRow: {
    marginTop: "20px",
    paddingTop: "20px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    display: "flex",
    flexDirection: "column",
    rowGap: "10px",
    fontFamily: tokens.fontBody,
    fontSize: "12px",
    color: tokens.colorTextDim,
  },
  textLink: {
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: tokens.colorGreen,
    textDecorationLine: "none",
    cursor: "pointer",
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
  inlineLink: {
    color: tokens.colorGreen,
    textDecorationLine: "none",
    fontWeight: 600,
    transitionProperty: "color",
    transitionDuration: tokens.transition,
    ":hover": { color: tokens.colorText },
  },
});
