import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useSidebarStyles = makeStyles({
  side: {
    gridArea: "side",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: tokens.colorBorder,
    backgroundColor: tokens.colorBg1,
    display: "flex",
    flexDirection: "column",
    paddingTop: "18px",
    paddingBottom: "18px",
    paddingLeft: "12px",
    paddingRight: "12px",
  },
  sectionLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.28em",
    color: tokens.colorTextFaint,
    paddingLeft: "6px",
    paddingRight: "6px",
    paddingBottom: "10px",
  },
  sectionLabelTopGap: {
    marginTop: "22px",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "9px",
    paddingBottom: "9px",
    paddingLeft: "10px",
    paddingRight: "10px",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: "2px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
    borderTopRightRadius: "3px",
    borderBottomRightRadius: "3px",
    backgroundColor: "transparent",
    color: tokens.colorTextDim,
    fontSize: "12px",
    letterSpacing: "0.04em",
    textAlign: "left",
    textDecorationLine: "none",
    transitionProperty: "background-color, color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorText,
    },
  },
  navItemActive: {
    backgroundColor: tokens.colorGreenSoft,
    color: tokens.colorGreen,
    borderLeftColor: tokens.colorGreen,
  },
  libraryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "7px",
    paddingBottom: "7px",
    paddingLeft: "10px",
    paddingRight: "10px",
    fontSize: "12px",
    color: tokens.colorTextDim,
  },
  libraryName: {
    display: "flex",
    alignItems: "center",
    columnGap: "8px",
  },
  libraryDot: {
    width: "5px",
    height: "5px",
    borderRadius: "999px",
  },
  libraryDotOk: { backgroundColor: tokens.colorGreen },
  libraryDotWarn: { backgroundColor: tokens.colorYellow },
  libraryCount: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    color: tokens.colorTextMuted,
  },
  spacer: { flex: 1 },
  userRow: {
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "8px",
    paddingRight: "8px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorderSoft,
    marginTop: "12px",
  },
  avatar: {
    width: "30px",
    height: "30px",
    borderTopLeftRadius: "4px",
    borderTopRightRadius: "4px",
    borderBottomLeftRadius: "4px",
    borderBottomRightRadius: "4px",
    background: `linear-gradient(140deg, ${tokens.colorGreenDeep}, ${tokens.colorGreen})`,
    color: tokens.colorGreenInk,
    fontWeight: "700",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userTextCol: { flex: 1 },
  userName: { fontSize: "12px", color: tokens.colorText },
  userMeta: {
    fontSize: "10px",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
  },
  chev: {
    color: tokens.colorTextMuted,
    transform: "rotate(-90deg)",
  },
});
