import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const useEditProfilePaneStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 18px",
    borderBottom: `1px solid ${tokens.colorBorder}`,
    flexShrink: "0",
  },
  headerTitle: {
    fontFamily: tokens.fontHead,
    fontSize: "18px",
    letterSpacing: "0.06em",
    color: tokens.colorWhite,
  },
  closeBtn: {
    width: "28px",
    height: "28px",
    background: "rgba(0,0,0,0.3)",
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.colorMuted,
    cursor: "pointer",
    transitionProperty: "color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorWhite,
      border: `1px solid ${tokens.colorBorder2}`,
    },
  },

  // ── Form body ─────────────────────────────────────────────────────────────
  body: {
    flex: "1",
    overflowY: "auto",
    padding: "20px 18px",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },

  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: tokens.colorMuted2,
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    backgroundColor: tokens.colorSurface2,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "12px",
    fontFamily: tokens.fontBody,
    outlineStyle: "none",
    transitionProperty: "border-color",
    transitionDuration: tokens.transition,
    ":focus": {
      border: `1px solid ${tokens.colorRed}`,
    },
    "::placeholder": {
      color: tokens.colorMuted2,
    },
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    backgroundColor: tokens.colorSurface2,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "12px",
    fontFamily: tokens.fontBody,
    outlineStyle: "none",
    cursor: "pointer",
    transitionProperty: "border-color",
    transitionDuration: tokens.transition,
    ":focus": {
      border: `1px solid ${tokens.colorRed}`,
    },
    appearance: "none",
    boxSizing: "border-box",
  },

  // ── Extension chips ───────────────────────────────────────────────────────
  extChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px",
  },
  extChip: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 10px",
    borderRadius: tokens.radiusSm,
    fontSize: "11px",
    fontWeight: "600",
    fontFamily: tokens.fontMono,
    cursor: "pointer",
    border: `1px solid ${tokens.colorBorder}`,
    backgroundColor: tokens.colorSurface3,
    color: tokens.colorMuted,
    transitionProperty: "background, border-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      border: `1px solid ${tokens.colorBorder2}`,
      color: tokens.colorWhite,
    },
  },
  extChipActive: {
    backgroundColor: tokens.colorRedDim,
    border: `1px solid ${tokens.colorRedBorder}`,
    color: tokens.colorRed,
  },

  // ── Error ─────────────────────────────────────────────────────────────────
  errorMsg: {
    fontSize: "11px",
    color: tokens.colorRed,
    padding: "8px 12px",
    backgroundColor: tokens.colorRedDim,
    border: `1px solid ${tokens.colorRedBorder}`,
    borderRadius: tokens.radiusSm,
  },

  // ── Path input row ────────────────────────────────────────────────────────
  pathRow: {
    display: "flex",
    gap: "6px",
    alignItems: "stretch",
  },
  pathInput: {
    flex: "1",
    padding: "8px 12px",
    backgroundColor: tokens.colorSurface2,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "12px",
    fontFamily: tokens.fontMono,
    outlineStyle: "none",
    transitionProperty: "border-color",
    transitionDuration: tokens.transition,
    ":focus": {
      border: `1px solid ${tokens.colorRed}`,
    },
    "::placeholder": {
      color: tokens.colorMuted2,
    },
    boxSizing: "border-box",
  },
  browseBtn: {
    padding: "0 10px",
    backgroundColor: tokens.colorSurface2,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorMuted,
    fontSize: "11px",
    fontWeight: "600",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transitionProperty: "color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorWhite,
      border: `1px solid ${tokens.colorBorder2}`,
    },
  },
  browseBtnActive: {
    color: tokens.colorWhite,
    border: `1px solid ${tokens.colorBorder2}`,
  },

  // ── Directory browser panel ───────────────────────────────────────────────
  browserPanel: {
    marginTop: "4px",
    backgroundColor: tokens.colorSurface3,
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    overflow: "hidden",
  },
  browserBreadcrumb: {
    padding: "6px 10px",
    fontSize: "10px",
    fontFamily: tokens.fontMono,
    color: tokens.colorMuted,
    borderBottom: `1px solid ${tokens.colorBorder}`,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  browserList: {
    maxHeight: "160px",
    overflowY: "auto",
  },
  browserEntry: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 10px",
    fontSize: "12px",
    color: tokens.colorMuted,
    cursor: "pointer",
    borderBottom: `1px solid rgba(255,255,255,0.03)`,
    background: "transparent",
    width: "100%",
    textAlign: "left",
    transitionProperty: "background, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: "rgba(255,255,255,0.04)",
      color: tokens.colorWhite,
    },
  },
  browserEntryUp: {
    color: tokens.colorMuted2,
    fontStyle: "italic",
  },
  browserEmpty: {
    padding: "12px 10px",
    fontSize: "11px",
    color: tokens.colorMuted2,
    textAlign: "center",
  },
  browserActions: {
    padding: "6px 10px",
    borderTop: `1px solid ${tokens.colorBorder}`,
    display: "flex",
    justifyContent: "flex-end",
  },
  browserSelectBtn: {
    padding: "4px 10px",
    backgroundColor: tokens.colorRed,
    border: `1px solid ${tokens.colorRed}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "11px",
    fontWeight: "600",
    cursor: "pointer",
    transitionProperty: "background",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorRedDark,
    },
  },

  // ── Footer actions ────────────────────────────────────────────────────────
  footer: {
    padding: "14px 18px",
    borderTop: `1px solid ${tokens.colorBorder}`,
    display: "flex",
    gap: "8px",
    flexShrink: "0",
  },
  footerMain: {
    display: "flex",
    gap: "8px",
    flex: "1",
  },
  footerDelete: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "100%",
  },
  deleteConfirmMsg: {
    fontSize: "11px",
    color: "rgba(206,17,38,0.8)",
    padding: "6px 10px",
    backgroundColor: tokens.colorRedDim,
    border: `1px solid ${tokens.colorRedBorder}`,
    borderRadius: tokens.radiusSm,
    lineHeight: "1.4",
  },
  deleteConfirmRow: {
    display: "flex",
    gap: "6px",
  },
  btnDelete: {
    padding: "9px 12px",
    backgroundColor: "transparent",
    border: `1px solid rgba(206,17,38,0.3)`,
    borderRadius: tokens.radiusSm,
    color: "rgba(206,17,38,0.6)",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    transitionProperty: "color, border-color, background",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorRed,
      border: `1px solid ${tokens.colorRed}`,
      backgroundColor: tokens.colorRedDim,
    },
    ":disabled": {
      opacity: "0.5",
      cursor: "default",
    },
  },
  btnCancel: {
    flex: "1",
    padding: "9px 0",
    backgroundColor: "transparent",
    border: `1px solid ${tokens.colorBorder}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorMuted,
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    transitionProperty: "color, border-color",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorWhite,
      border: `1px solid ${tokens.colorBorder2}`,
    },
  },
  btnSave: {
    flex: "2",
    padding: "9px 0",
    backgroundColor: tokens.colorRed,
    border: `1px solid ${tokens.colorRed}`,
    borderRadius: tokens.radiusSm,
    color: tokens.colorWhite,
    fontSize: "12px",
    fontWeight: "700",
    letterSpacing: "0.04em",
    cursor: "pointer",
    transitionProperty: "background",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorRedDark,
    },
    ":disabled": {
      opacity: "0.5",
      cursor: "default",
    },
  },
});
