import { makeStyles } from "@griffel/react";
import { tokens } from "../../styles/tokens.js";

export const useAppHeaderStyles = makeStyles({
  header: {
    gridArea: "head",
    position: "relative",
    zIndex: 10,
    display: "grid",
    gridTemplateColumns: `${tokens.sidebarWidth} 1fr auto`,
    backgroundImage:
      "linear-gradient(180deg, rgba(20,28,24,0.55) 0%, rgba(8,11,10,0.78) 100%)",
    backgroundColor: "rgba(8,11,10,0.62)",
    backdropFilter: "blur(20px) saturate(1.6)",
    WebkitBackdropFilter: "blur(20px) saturate(1.6)",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(37,48,42,0.45)",
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.05), inset 0 -1px 0 rgba(0,0,0,0.18), 0 6px 22px rgba(0,0,0,0.42)",
  },
  brandCell: {
    display: "flex",
    alignItems: "center",
    paddingLeft: "18px",
    paddingRight: "18px",
  },
  brand: {
    display: "flex",
    alignItems: "baseline",
    fontFamily: tokens.fontHead,
    fontSize: "26px",
    letterSpacing: "-0.02em",
    lineHeight: "1",
  },
  brandX: {
    color: tokens.colorGreen,
    textShadow: `0 0 12px ${tokens.colorGreenGlow}`,
  },
  brandWord: { color: tokens.colorText },

  searchCell: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    columnGap: "10px",
    width: "380px",
    justifySelf: "start",
    marginTop: "8px",
    marginBottom: "8px",
    marginLeft: "14px",
    marginRight: "0",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: "transparent",
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.55) 22%, rgba(20,28,24,0.55) 78%, rgba(20,28,24,0) 100%)",
    outlineWidth: "0",
    transitionProperty: "background-image",
    transitionDuration: tokens.transition,
  },
  searchCellHover: {
    ":hover": {
      animationName: {
        "0%, 100%": {
          backgroundImage:
            "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.45) 22%, rgba(20,28,24,0.45) 78%, rgba(20,28,24,0) 100%)",
        },
        "50%": {
          backgroundImage:
            "linear-gradient(90deg, rgba(28,40,34,0) 0%, rgba(28,40,34,0.7) 22%, rgba(28,40,34,0.7) 78%, rgba(28,40,34,0) 100%)",
        },
      },
      animationDuration: "3.4s",
      animationIterationCount: "infinite",
      animationTimingFunction: "ease-in-out",
    },
  },
  searchCellFocused: {
    backgroundImage:
      "linear-gradient(90deg, rgba(20,28,24,0) 0%, rgba(20,28,24,0.78) 22%, rgba(20,28,24,0.78) 78%, rgba(20,28,24,0) 100%)",
  },
  searchIcon: {
    color: tokens.colorGreen,
    display: "flex",
    alignItems: "center",
    flexShrink: "0",
  },
  inputWrap: {
    position: "relative",
    flex: "1",
    display: "flex",
    alignItems: "center",
    height: "100%",
    minWidth: "0",
  },
  mirror: {
    position: "absolute",
    left: "0",
    top: "50%",
    transform: "translateY(-50%)",
    visibility: "hidden",
    pointerEvents: "none",
    whiteSpace: "pre",
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.08em",
  },
  searchInput: {
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    backgroundImage: "none",
    borderTopWidth: "0",
    borderRightWidth: "0",
    borderBottomWidth: "0",
    borderLeftWidth: "0",
    outlineStyle: "none",
    color: tokens.colorText,
    fontFamily: tokens.fontMono,
    fontSize: "12px",
    letterSpacing: "0.08em",
    caretColor: "transparent",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "0",
    paddingRight: "16px",
    "::placeholder": {
      color: tokens.colorTextMuted,
      letterSpacing: "0.12em",
      textTransform: "uppercase",
    },
  },
  caret: {
    position: "absolute",
    top: "50%",
    width: "8px",
    height: "16px",
    marginTop: "-8px",
    backgroundColor: tokens.colorGreen,
    borderTopLeftRadius: "1px",
    borderTopRightRadius: "1px",
    borderBottomLeftRadius: "1px",
    borderBottomRightRadius: "1px",
    pointerEvents: "none",
    boxShadow: `0 0 6px ${tokens.colorGreen}, 0 0 16px ${tokens.colorGreenGlow}`,
    animationName: {
      "0%, 100%": { opacity: "1", transform: "scaleY(1)" },
      "50%": { opacity: "0.25", transform: "scaleY(0.86)" },
    },
    animationDuration: "1.05s",
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },

  suggestions: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: "0",
    right: "0",
    listStyleType: "none",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "0",
    paddingRight: "0",
    marginTop: "0",
    marginBottom: "0",
    marginLeft: "0",
    marginRight: "0",
    backgroundColor: "rgba(10,13,12,0.92)",
    backdropFilter: "blur(18px) saturate(1.4)",
    WebkitBackdropFilter: "blur(18px) saturate(1.4)",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: tokens.colorBorder,
    borderRightColor: tokens.colorBorder,
    borderBottomColor: tokens.colorBorder,
    borderLeftColor: tokens.colorBorder,
    borderTopLeftRadius: tokens.radiusMd,
    borderTopRightRadius: tokens.radiusMd,
    borderBottomLeftRadius: tokens.radiusMd,
    borderBottomRightRadius: tokens.radiusMd,
    boxShadow: "0 18px 40px rgba(0,0,0,0.55)",
    zIndex: 50,
    maxHeight: "320px",
    overflowY: "auto",
    animationName: {
      from: { opacity: "0", transform: "translateY(-4px)" },
      to: { opacity: "1", transform: "translateY(0)" },
    },
    animationDuration: "0.14s",
    animationTimingFunction: "ease-out",
    animationFillMode: "both",
  },
  suggGroupLabel: {
    fontFamily: tokens.fontMono,
    fontSize: "9px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: tokens.colorTextFaint,
    paddingTop: "8px",
    paddingBottom: "6px",
    paddingLeft: "14px",
    paddingRight: "14px",
  },
  suggestionItem: {
    display: "flex",
    flexDirection: "column",
    rowGap: "2px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "14px",
    paddingRight: "14px",
    cursor: "pointer",
    transitionProperty: "background-color, color",
    transitionDuration: tokens.transition,
    ":hover": {
      backgroundColor: tokens.colorGreenSoft,
    },
  },
  suggLabel: {
    fontFamily: tokens.fontBody,
    fontSize: "13px",
    color: tokens.colorText,
  },
  suggMeta: {
    fontFamily: tokens.fontMono,
    fontSize: "10px",
    letterSpacing: "0.08em",
    color: tokens.colorTextMuted,
  },
  suggEmpty: {
    paddingTop: "14px",
    paddingBottom: "14px",
    paddingLeft: "14px",
    paddingRight: "14px",
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    color: tokens.colorTextMuted,
    textAlign: "center",
  },

  actionsCell: {
    display: "flex",
    alignItems: "center",
    paddingLeft: "8px",
    paddingRight: "18px",
  },
  scanBtn: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "14px",
    paddingRight: "14px",
    backgroundColor: "transparent",
    backgroundImage: "none",
    borderTopWidth: "0",
    borderRightWidth: "0",
    borderBottomWidth: "0",
    borderLeftWidth: "0",
    color: tokens.colorTextMuted,
    fontFamily: tokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    cursor: "pointer",
    whiteSpace: "nowrap",
    outlineStyle: "none",
    transitionProperty: "color, text-shadow",
    transitionDuration: tokens.transition,
    ":hover": {
      color: tokens.colorGreen,
      textShadow: `0 0 6px ${tokens.colorGreen}, 0 0 16px ${tokens.colorGreenGlow}`,
    },
  },
  scanIcon: {
    display: "flex",
    alignItems: "center",
  },
  scanIconSpinning: {
    animationName: { to: { transform: "rotate(360deg)" } },
    animationDuration: "1.1s",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
});
