import { makeStyles } from "@griffel/react";

import { tokens } from "~/styles/tokens";

export const usePageSkeletonStyles = makeStyles({
  skeleton: {
    background: "linear-gradient(90deg, #161616 25%, #1C1C1C 50%, #161616 75%)",
    backgroundSize: "200% 100%",
    animationName: {
      "0%": { backgroundPosition: "200% 0" },
      "100%": { backgroundPosition: "-200% 0" },
    },
    animationDuration: "1.6s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
    borderRadius: "4px",
  },

  statsRow: {
    display: "flex",
    alignItems: "center",
    borderBottom: `1px solid ${tokens.colorBorder}`,
    backgroundColor: tokens.colorSurface,
    flexShrink: "0",
  },
  statCell: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    padding: "14px 28px",
    borderRight: `1px solid ${tokens.colorBorder}`,
  },
  filterBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    borderBottom: `1px solid ${tokens.colorBorder}`,
    flexShrink: "0",
    backgroundColor: tokens.colorSurface,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: "12px",
    padding: "20px",
  },
  posterCard: {
    borderRadius: tokens.radiusMd,
    overflow: "hidden",
    backgroundColor: tokens.colorSurface2,
  },
  posterImg: {
    paddingBottom: "150%",
  },
  posterInfo: {
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  hero: {
    height: "220px",
    flexShrink: "0",
  },
  locationBar: {
    height: "38px",
    borderBottom: `1px solid ${tokens.colorBorder}`,
    display: "flex",
    alignItems: "center",
    padding: "0 24px",
    flexShrink: "0",
  },
  dirHeader: {
    display: "grid",
    gridTemplateColumns: "32px 1fr 120px 160px 80px 80px",
    padding: "0 16px",
    height: "32px",
    alignItems: "center",
    gap: "8px",
    borderBottom: `1px solid ${tokens.colorBorder}`,
    flexShrink: "0",
    backgroundColor: tokens.colorSurface,
  },
  dirRow: {
    display: "grid",
    gridTemplateColumns: "32px 1fr 120px 160px 80px 80px",
    padding: "0 16px",
    height: "52px",
    alignItems: "center",
    gap: "8px",
    borderBottom: `1px solid rgba(255,255,255,0.04)`,
  },
  listItem: {
    display: "grid",
    gridTemplateColumns: "60px 1fr auto auto",
    alignItems: "center",
    gap: "12px",
    padding: "10px 0",
    borderBottom: `1px solid rgba(255,255,255,0.04)`,
  },
  listThumb: {
    width: "60px",
    height: "34px",
    borderRadius: "4px",
  },
  listInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  settingsShell: {
    height: "100%",
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    paddingTop: tokens.headerHeight,
    boxSizing: "border-box",
  },
  settingsNav: {
    borderRight: `1px solid ${tokens.colorBorder}`,
    backgroundColor: tokens.colorBg1,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  settingsNavItem: {
    paddingTop: "9px",
    paddingBottom: "9px",
    paddingLeft: "12px",
    paddingRight: "12px",
  },
  settingsBody: {
    overflowY: "auto",
    padding: "32px 40px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  settingsRow: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    paddingBottom: "14px",
    borderBottom: `1px solid ${tokens.colorBorderSoft}`,
  },
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflow: "hidden",
  },
  scrollBody: {
    flex: "1",
    overflowY: "auto",
    padding: "24px",
  },
});
