/**
 * Design tokens — single source of truth for the Moran visual language.
 * Used by all Griffel makeStyles() calls.
 */
export const tokens = {
  colorRed:        "#CE1126",
  colorRedDark:    "#A50D1E",
  colorRedDim:     "rgba(206, 17, 38, 0.12)",
  colorRedBorder:  "rgba(206, 17, 38, 0.28)",
  colorBlack:      "#080808",
  colorSurface:    "#0F0F0F",
  colorSurface2:   "#161616",
  colorSurface3:   "#1C1C1C",
  colorBorder:     "#222222",
  colorBorder2:    "#2E2E2E",
  colorWhite:      "#FFFFFF",
  colorOffWhite:   "#F0EEEB",
  colorMuted:      "#666666",
  colorMuted2:     "#3E3E3E",
  colorGreen:      "#27AE60",
  colorYellow:     "#F5C518",
  fontHead:        "'Bebas Neue', sans-serif",
  fontBody:        "'Inter', sans-serif",
  fontMono:        "'SF Mono', 'Fira Code', monospace",
  radiusSm:        "4px",
  radiusMd:        "8px",
  radiusLg:        "12px",
  radiusFull:      "9999px",
  space1:          "4px",
  space2:          "8px",
  space3:          "12px",
  space4:          "16px",
  space5:          "20px",
  space6:          "24px",
  transition:      "0.15s",
  transitionSlow:  "0.25s",
  headerHeight:    "52px",
  sidebarWidth:    "220px",
  sidebarCollapsedWidth: "52px",
} as const;
